- README.md
Closes # no issue is up for this.
Small typo present in the README example
A semi colon was used after id instead of a colon, so the example doesn't work without updating it after copying the example.
No error on example
N/A
> refactor(readme): fix example typo from ; to :

- .changeset/nice-planes-rhyme.md
- .changeset/rich-radios-develop.md
- .xstate/number-input.js
- packages/core/src/machine.ts
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/number-input/src/number-input.machine.ts
Closes #80
When you render multiple instances of the Number Input, the initial value of every instance following the first instance quickly gets replaced with the initial value of the first instance (after briefly being correctly set to their own initial values).
This PR fixes that.
> fix(number-input): initial values

- .changeset/lovely-moose-mate.md
- .xstate/pin-input.js
- packages/machines/pin-input/src/pin-input.connect.ts
- packages/machines/pin-input/src/pin-input.machine.ts
Closes #84
Fix issue where pin input allowed double characters when pressing two numbers at the same time
Adds multiple values in the input
Allows only one value per input, regardless of input method
No
> fix: pin input allows double characters

- .changeset/funny-clocks-invite.md
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/menu/src/menu.connect.ts
- packages/machines/popover/src/popover.connect.ts
- packages/machines/tooltip/src/tooltip.connect.ts
- packages/utilities/popper/src/get-styles.ts
Closes #87 
Makes the arrow rotation dependent on the placement. This makes it easier to style the borders facing the trigger.
Rotation of arrow is no longer just 45deg but now also 135, 225, 315 if the position is bottom, left, top or right resp.
Shouldn't affect anyone as 45deg is the same as the other values. Only if users were styling their arrow dependent on placement already
> feat: arrow rotation based on placement

- .changeset/funny-experts-boil.md
- .changeset/purple-owls-battle.md
- packages/machines/popover/src/popover.connect.ts
- packages/utilities/popper/src/get-placement.ts
- packages/utilities/popper/src/middleware.ts
- shared/style.ts
This PR improves the transform-origin calculation of popper-related components such that its origin starts from the arrow position. This improves the UX for apps with subtle scale transitions/animations.
We've hardcoded the transform origins
Now dynamic, based on placement and if the arrow is rendered.
No
> fix: improve popper transform origin calculations

- .changeset/swift-meals-dress.md
- packages/machines/number-input/src/number-input.connect.ts
Closes #99
Add an extra dataset to identify the number-inputs increment and decrement parts.
We only have the `data-part=spin-button` without additional info about if it's the increment or decrement button
We now include a `data-type=(increment|decrement)` to help identify the elements via CSS or JS.
No
> numberinput: update parts dataset

- .changeset/seven-lizards-shout.md
- .xstate/number-input.js
- packages/machines/number-input/src/number-input.machine.ts
Closes #103
Fix issue where Firefox doesn't send pointerup event for disabled buttons, requiring an explicit tracking of the disabled state to execute the proper transition.
No
> fix: number input firefox issue

- plop/machine/src/{{machine}}.machine.ts.hbs
Fixed code structure error in machine generate plop
`createMachine` closing bracket came before the parameter closing curly braces
> fix: error in generate machine plop

- packages/machines/tags-input/src/tags-input.connect.ts
Removed redundant optional chaining operator, in tags input keymap execution.
> chore: removes Redundant optional chaining operator

- .changeset/cuddly-swans-pay.md
- packages/machines/range-slider/src/range-slider.connect.ts
- packages/machines/range-slider/src/range-slider.dom.ts
- packages/machines/range-slider/src/range-slider.style.ts
- packages/machines/slider/src/slider.connect.ts
- packages/machines/slider/src/slider.dom.ts
- packages/machines/slider/src/slider.style.ts
This PR cleans up the style calculations in the slider and range-slider components. We now expose the positions of the thumbs and range via CSS to allow users to build elements (like tooltips) that follow the thumb position.
Works, but can be improved.
Scoped CSS variables to the root element for better access to position data in CSS
No
> refactor: slider component

- .changeset/chilled-toys-pull.md
- packages/machines/range-slider/src/range-slider.machine.ts
- packages/machines/slider/src/slider.machine.ts
Closes #131
`disabled` is always false by default, even when we set it to true in the initial context
The `trackFieldsetDisabled` activity only sets `disabled` in the context to true, if the fieldset is disabled.
> fix(slider): `disabled` is always false by default

- .changeset/perfect-wombats-relax.md
- packages/machines/number-input/src/number-input.machine.ts
- packages/machines/number-input/src/number-input.utils.ts
Issue in `setValue` action caused bugs in `setToMin` and `setToMax` API methods
Those API methods don't work
They work now
> Fix: setvalue error in number input

- .changeset/cool-stingrays-tie.md
- packages/machines/rating/src/rating.connect.ts
> Rating hidden input uses `value` without `onChange` handler
> Fix rating defaultvalue

- .changeset/chilly-moose-swim.md
- .xstate/tags-input.js
- e2e/tags-input.e2e.ts
- packages/machines/tags-input/src/tags-input.machine.ts
Closes #238
When a tag is focused, we transition to the `navigating:tag` state. `delete` deletes the focused tag and `enter` transitions to the `editing:tag` state, with the `id` of the focused tag in context under `focusedId`.
Now when a tag is deleted, we remain in the `navigating:tag` state, and focus the new last tag, this approach allows the user to keep pressing delete to remove multiple tags, without having to focus them individually.
So when the user deletes the last tag, we're still in the `navigating:tag` state. But now, there's no more tags. The first issue, is as we focus the previous tag after deleting a tag, we don't account for when there's no previous tag (when all tags are deleted), so the id of the last deleted tag remains in context as focused tag.
Now when the user …
> Fix: tag input edit non existent tag

- .changeset/clean-berries-design.md
- examples/next-ts/pages/toast.tsx
- packages/machines/toast/src/toast.connect.ts
- packages/machines/toast/src/toast.dom.ts
Closes #235
Toast Description was not exposed in the `connect` method.
> fix(toast) description not exposed

- .changeset/funny-countries-bake.md
- packages/machines/number-input/package.json
- packages/machines/number-input/src/number-input.connect.ts
- packages/machines/number-input/src/number-input.machine.ts
- pnpm-lock.yaml
Closes #265
Fix issue where the number input doesn't trigger change event when set programmatically. This was caused by the fact that we use the "controlled" state. Going forward, we'll stick with uncontrolled since this is the DOM works by default.
No
> fix: number input dispatch change

- .changeset/sharp-candles-hammer.md
- .changeset/warm-donuts-hug.md
- .changeset/wdfarm-dfuts-hug.md
- .xstate/menu.js
- packages/machines/menu/src/menu.connect.ts
- packages/machines/menu/src/menu.machine.ts
- packages/utilities/dom/src/event.ts
Closes #283 
This PR fixes the issue where the menu doesn't trigger selects on mobile. This was caused by the fact that `ctx.activeId` was undefined/null.
> Fix menu doesn't trigger select on mobile

- .changeset/smooth-zoos-march.md
- packages/machines/tooltip/src/tooltip.connect.ts
- packages/machines/tooltip/src/tooltip.types.ts
Add `disabled` to tooltip context to allow disabling tooltips
> Allow disabling tooltip by adding disabled to context

- .changeset/eleven-shirts-speak.md
- tsup.config.js
Currently Cypress doesn't support optional chaining and the nullish coalescing operator, this ensures the packages are transpiled with the `es2019` target.
Currently, code is transpiled with `??`
```javascript
var runIfFn = (v, ...a) => {
const res = typeof v === "function" ? v(...a) : v;
return res ?? void 0;
};
```
This fix will transpile the above like:
```javascript
var runIfFn = (v, ...a) => {
const res = typeof v === "function" ? v(...a) : v;
return res != null ? res : void 0;
};
```
No.
> fix: ensure code is transpiled with es2019 target

- .changeset/spotty-boxes-sing.md
- examples/next-ts/pages/rating.tsx
- examples/solid-ts/src/pages/rating.tsx
- examples/vue-ts/src/pages/rating.tsx
- packages/core/src/machine.ts
- packages/frameworks/react/src/use-machine.ts
- packages/frameworks/solid/src/use-machine.ts
- packages/frameworks/svelte/src/use-machine.ts
- packages/frameworks/vue/src/use-machine.ts
- shared/src/controls.ts
This PR improves the react `useMachine` to support readonly or controlled context values.
This hook sometimes run into "Maximum depth" aka infinite loop issues when passed object types (object, array, functions)
Works as intended
No
> Fix: controlled context and react

- .changeset/happy-buses-rest.md
- packages/machines/toast/src/index.ts
Resolves issue in Ark `ToastOptions can not be named`
> fix(toasts): export toast options

- .changeset/tame-terms-compete.md
- packages/core/src/types.ts
- packages/frameworks/react/src/use-actor.ts
- packages/frameworks/react/src/use-machine.ts
- packages/machines/combobox/src/combobox.machine.ts
- packages/machines/editable/src/editable.machine.ts
- packages/machines/number-input/src/number-input.machine.ts
- packages/machines/tags-input/src/tags-input.machine.ts
In previous versions of Zag.js, we needed a "magic" property, `hookSync` which helped Valtio synchronously update values when using controlled inputs.
By default, Zag.js uses uncontrolled inputs for better SSR and progressive enhancement. We also sync with the DOM manually using the onChange/onInput callback.
Max call stack exceeded error when using any machine with this `hookSync` option and using a controlled context
Works as expected
No
> fix: remove hook sync

- .changeset/forty-hornets-hug.md
- packages/machines/checkbox/src/checkbox.connect.ts
- packages/machines/checkbox/src/checkbox.types.ts
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/combobox/src/combobox.types.ts
- packages/machines/editable/src/editable.connect.ts
- packages/machines/editable/src/editable.types.ts
- packages/machines/number-input/src/number-input.connect.ts
- packages/machines/number-input/src/number-input.types.ts
- packages/machines/pin-input/src/pin-input.connect.ts
- packages/machines/pin-input/src/pin-input.types.ts
- packages/machines/radio/src/radio.connect.ts
- packages/machines/radio/src/radio.types.ts
- packages/machines/range-slider/src/range-slider.connect.ts
- packages/machines/range-slider/src/range-slider.types.ts
- packages/machines/rating/src/rating.connect.ts
- packages/machines/rating/src/rating.types.ts
- packages/machines/slider/src/slider.connect.ts
- packages/machines/slider/src/slider.types.ts
- packages/machines/tags-input/src/tags-input.connect.ts
- packages/machines/tags-input/src/tags-input.types.ts
Add `form` attribute to all form related elements
> chore: add `form` attribute to all form related elements

- .changeset/clever-baboons-do.md
- e2e/checkbox.e2e.ts
- packages/machines/checkbox/src/checkbox.connect.ts
`readonly` attribute only applies to text inputs, not checkboxes and radios according to the [HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly)
related issue in react-aria: https://github.com/adobe/react-spectrum/issues/1413
checkbox inputProps has unsupported attribute `readonly`.
checkbox inputProps has `aria-readonly` which is allowed on checkbox role.
> fix(checkbox): use aria-readonly instead of readonly attribute

- .changeset/empty-weeks-tan.md
- packages/machines/checkbox/src/checkbox.types.ts
Remove unused `aria-invalid` property in PublicContext.
`aria-invalid` property is included PublicContext, but `inputProps["aria-invalid"]` is determined from `isInvalid` and `aria-invalid` is never used in current code.
`aria-invalid` property is removed from PublicContext.
> refactor(checkbox): remove unused aria-invalid property in PublicContext

- .changeset/calm-rules-worry.md
- .xstate/checkbox.js
- packages/machines/checkbox/src/checkbox.machine.ts
state is not updated during transition, so invokeOnChange should be called on entry.
onChange emits `false` when value turns `false` -> `true`,
and emits `true` when value turns `true` -> `false`.
onChange emits `true` when value turns `false` -> `true`,
and emits `false` when value turns `true` -> `false`.
> fix: checkbox onChange emitted value

- .changeset/warm-pumas-type.md
- examples/solid-ts/tsconfig.json
- examples/vue-ts/tsconfig.json
- packages/machines/checkbox/src/checkbox.connect.ts
Closes #411 
Updated rootprops to always target `label` html element and hold the html `for` attribute
> fix(checkbox): move for to label - rootprops

- .changeset/slow-pugs-reflect.md
- .xstate/accordion.js
- packages/machines/accordion/src/accordion.machine.ts
Closes OSS-489
Fix the issue where the value was reset infinitely when `value: []` and `multiple: false` is passed to the machine context.
Infinite loop
Works
No
> fix: accordion infinite loop

- .changeset/curvy-frogs-swim.md
- .changeset/old-lies-tap.md
- examples/next-ts/pages/range-slider.tsx
- examples/solid-ts/src/pages/range-slider.tsx
- examples/vue-ts/src/pages/range-slider.tsx
- packages/machines/range-slider/src/range-slider.connect.ts
- packages/machines/range-slider/src/range-slider.dom.ts
- packages/machines/range-slider/src/range-slider.machine.ts
- packages/machines/range-slider/src/range-slider.style.ts
- packages/machines/range-slider/src/range-slider.types.ts
- packages/machines/range-slider/src/range-slider.utils.ts
- packages/utilities/number/src/transform.ts
change `values` to `value` in rangeslider
> chore: change `values` to `value` in rangeslider

- .changeset/heavy-geese-beam.md
- e2e/pin-input.e2e.ts
- packages/machines/pin-input/src/pin-input.machine.ts
Closes #470
Fixes issue with pasting in non-empty field in pin input
Pasted value is truncated
Pasted value fully replaces current value
No
> fix(pin-input): paste in non-empty field #470

- .changeset/kind-hounds-bathe.md
- .xstate/hover-card.js
- packages/machines/hover-card/src/hover-card.connect.ts
- packages/machines/hover-card/src/hover-card.machine.ts
Add `open` and `close` functions to the hover card connect api:
Missing way to control the machine.
```ts
import * as hoverCard from "@zag-js/hover-card"
const api = hoverCard.connect(state, send, normalizeProps)
// call `open` to open the hover card
api.open()
// call `close` to close the hover card
api.close()
```
No
Prerequisite to [OSS-518](https://linear.app/chakra/issue/OSS-518/featreact-controlled-usage-of-hovercard-component)
> feat(hover-card): add manual open and close functions to the connect api

- .changeset/sour-cats-repeat.md
- packages/store/package.json
- pnpm-lock.yaml
Closes # 
`index.mjs` after `pnpm build`
```js
// src/index.ts
import { ref, snapshot, proxy, subscribe } from "valtio/vanilla";
import { proxyWithComputed, subscribeKey } from "valtio/utils";
export {
proxy,
proxyWithComputed,
ref,
snapshot,
subscribe,
subscribeKey
};
```
import from `valtio` is present in build result, `valtio` should be in `dependencies`, not `devDependencies`.
Following error occurs when I try to import `@zag-js/store` or packages that imports store.
```
../../.yarn/cache/@zag-js-store-npm-0.2.5-72f8f309
f2-7d41d3c8b7.zip/node_modules/@zag-js/store/dist/
index.d.ts(2,49): error TS2307: Cannot find module
'valtio/utils' or its corresponding type 
declarations.
```
Errors are resolved.
> fix(store): move valtio to deps from devDeps

- .changeset/spotty-pugs-add.md
- examples/next-ts/pages/radio-group.tsx
- packages/machines/radio-group/src/radio-group.connect.ts
- packages/machines/radio-group/src/radio-group.dom.ts
- packages/machines/radio-group/src/radio-group.machine.ts
Closes #501
- Add `clearValue` api
- Fix radio inputs not syncing when radio group value is cleared,
> feat: add radio clearValue api

- .changeset/shy-ties-dance.md
- e2e/radio-group.e2e.ts
- packages/machines/radio-group/src/radio-group.connect.ts
Closes #518
Added `aria-labelledby` to radio group for improved screen reader accessibility.
Screen readers do not read the label of a radio group.
Screen readers read the label of a radio group.
No
> feat: add aria-labelledby to radio group

- .changeset/itchy-timers-whisper.md
- .xstate/pressable.js
- packages/machines/pressable/src/pressable.machine.ts
* onPressEnd is already invoked on `pressed:in` -> `pressed:out` transition,
invoking onPressEnd in pressed:out DOC_POINTER_UP is wrong.
* after `pressed:in` -> `pressed:out` -> `pressed:in` -> DOC_POINTER_UP,
onPress should be invoked.
These bahaviors are compared from React Aria [usePress](https://react-spectrum.adobe.com/react-aria/usePress.html).
* POINTER_DOWN (idle -> pressed:in)
* POINTER_LEAVE (pressed:in -> pressed:out) [invoke onPressEnd]
* DOC_POINTER_UP (pressed:out -> idle) [invoke onPressEnd]
* POINTER_DOWN (idle -> pressed:in)
* POINTER_LEAVE (pressed:in -> pressed:out)
* POINTER_ENTER (pressed:out -> pressed:in)
* DOC_POINTER_UP (pressed:out -> idle) [**NOT** invoke onPress]
* POINTER_DOWN (idle -> pressed:in)
* POINTER_LEAVE (pressed:in -> pressed:out) [invoke onPressEnd] …
> fix: pressable event trigger

- .changeset/rotten-years-smell.md
- .xstate/combobox.js
- e2e/combobox.e2e.ts
- examples/next-ts/pages/combobox.tsx
- examples/solid-ts/src/pages/combobox.tsx
- examples/vue-ts/src/pages/combobox.tsx
- packages/machines/combobox/src/combobox.machine.ts
Closes #531
Combobox API clears selected option on `clearValue`
Selected option is not cleared on `clearValue`
Selected option is cleared on `clearValue`
No
> fix(#531): clear selected option on clear value

- .changeset/good-hornets-grow.md
- .xstate/menu.js
- examples/vue-ts/src/pages/menu-options.tsx
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/menu/src/menu.connect.ts
- packages/machines/menu/src/menu.machine.ts
- packages/machines/select/src/select.connect.ts
Closes #237
This PR fixes a long-standing issue where elements trigger a double-click event due to the implicit invocation of `element.click()` inside the actions.
Take this snippet of code:
```jsx
<div>
<button {...api.triggerProps}>
Actions <span aria-hidden>▾</span>
</button>
<div {...api.positionerProps}>
<ul {...api.contentProps} onClick={(e) => console.log("clicked", e)}>
<li {...api.getItemProps({ id: "edit" })}>Edit</li>
<li {...api.getItemProps({ id: "duplicate" })}>Duplicate</li>
<li {...api.getItemProps({ id: "delete" })}>Delete</li>
<li {...api.getItemProps({ id: "export" })}>Export...</li>
</ul>
</div>
</div>
```
The `onClick` will be fired twice due to the mentioned reason.
We now use the machine's send function to invoke the transition in the `onClick` function. This is …
> fix(select, combobox, menu): implicit click -> explicit send

- .changeset/silly-planets-run.md
- packages/utilities/interact-outside/src/get-window-frames.ts
Fixes an app breaking issue when cross origin frames are present on the page
Currently a DOMException error is thrown
> Uncaught DOMException: Permission denied to access property "document" on cross-origin object
The error is now caught allowing the app to continue working without those iframes
> fix(interact-outside): fix app breaking error with cross origin iframes

- .changeset/early-bananas-smash.md
- packages/machines/checkbox/src/checkbox.types.ts
Fix typo in `interactive` type description
> fix(checkbox): `slider` typo

- .changeset/ten-items-yell.md
- packages/machines/combobox/src/combobox.machine.ts
- packages/machines/combobox/src/combobox.types.ts
- packages/machines/editable/src/editable.machine.ts
- packages/machines/editable/src/editable.types.ts
- packages/machines/select/src/select.machine.ts
- packages/machines/select/src/select.types.ts
- packages/machines/tags-input/src/tags-input.machine.ts
- packages/machines/tags-input/src/tags-input.types.ts
This adds an `onInteractOutside ` hook to the context of tags-input, select, combobox and editable, to enable composition with other components (e.g. `combobox`).
Related PR: #522
By adding an `onInteractOutside ` to the tags input context, users can hook into the logic, which determines if an event should be treated as an outside interaction.
Example:
```ts
import { useId } from "react"
import * as tagsInput from "@zag-js/tags-input"
tagsInput.machine({
id: useId(),
onInteractOutside(event) {
if (comboboxContentEl.contains(event.target)) {
event.preventDefault()
}
},
})
```
No
> feat: expose interact outside in context

- .changeset/wise-turkeys-punch.md
- packages/machines/rating-group/src/rating-group.connect.ts
Closes #566
Fixed arrow down selecting previous instead of next star
> fix(rating): fix arrow down navigation

- .changeset/six-humans-agree.md
- examples/svelte-ts/src/pages/Accordion.svelte
- examples/svelte-ts/src/pages/Select.svelte
- packages/frameworks/svelte/src/get-attributes-and-handlers.ts
- packages/frameworks/svelte/src/normalize-attributes.ts
- packages/frameworks/svelte/src/normalize-handlers.ts
- packages/frameworks/svelte/src/normalize-props.ts
- packages/frameworks/svelte/src/types.ts
- packages/frameworks/svelte/src/zag.ts
- packages/types/src/prop-types.ts
> Add TS support for Svelte normalizer
Current behavior returns errors on TS with the "attributes" and "handlers". This modifications aims to solve that.
> When using the svelte normalizer, we expect the return to be an object with "attributes" and "handlers" instead.
No
> fix(types): fix handlers and attributes types

- examples/next-ts/pages/switch.tsx
- examples/solid-ts/src/pages/switch.tsx
- examples/vue-ts/src/pages/switch.tsx
remove external input type from switch examples
> chore(switch): remove external input type from switch examples

- .changeset/olive-geese-fly.md
- packages/machines/switch/src/switch.machine.ts
This PR resolves the issue with the Switch `setChecked` not working, which was introduced in commit 7eaa3539bf11f97bf1d0f8c5cdbbe848e24f7f0b. The cause was a change in the `dispatchInputCheckedEvent` function, but the corresponding function call in the Switch component was not updated. This PR updates the function call to ensure the `setChecked` works as expected.
> fix(switch): setChecked not working issue

- .changeset/friendly-toys-hear.md
- packages/utilities/popper/src/get-placement.ts
`placement.offset` was not always being applied because `placement.gutter` took precedence over `placement.offset`
`placement.gutter` is ignored when both `placement.offset` and `placement.gutter` are provided.
However, `placement.gutter` is provided from `defaultOptions`, so `placement.offset` is always ignored.
`placement.offset` is applied when both `placement.offset` and `placement.gutter` are provided.
> fix(popper): offset is ignored from default gutter

- .changeset/light-beds-obey.md
- packages/utilities/dom-query/src/platform.ts
- packages/utilities/focus-visible/package.json
- packages/utilities/focus-visible/src/index.ts
- packages/utilities/number/src/number.ts
- pnpm-lock.yaml
This PR adjusts isBrowser detection to not rely on the window variable, which can be declared in various environments, such as e.g. Deno.
Currently the dom check will pass in environments that declare window variable despite not being a browser/not having a document. It can leads to the events being added on a server or a errors in case of reading values of document after checking if only window is declared.
It adjusts the check to validate the existence of document variable, which is recommended afaik.
Prior art: https://github.com/TanStack/virtual/pull/516 https://github.com/framer/motion/pull/1522 https://remix.run/docs/en/1.16.1/pages/gotchas#typeof-window-checks
I assume no 😃 
I wasn't sure about the changesets tbh, so I didn't generate them.
> fix: adjust isDom detection

- .changeset/poor-seals-cross.md
- packages/machines/radio-group/src/radio-group.machine.ts
- packages/machines/radio-group/src/radio-group.types.ts
Closes https://github.com/chakra-ui/ark/issues/1129
fix segmented control not transitioning after first render
> fix: segmented control not transitioning after first render

- .changeset/few-rats-pay.md
- packages/machines/switch/src/switch.connect.ts
Closes #738 and #740
Makes `setChecked` actually update the state for checkbox and switch
`setChecked` calls the wrong method
`setChecked` actually update the state for checkbox and switch
No
> Fixes setChecked for Checkbox and Switch components

- website/data/snippets/vue-sfc/hover-card/usage.mdx
The teleport in the Hover card (vue sfc) component's code sample is imported from @zag-js/vue, but must be imported from vue for it to work.
https://zagjs.com/components/react/hover-card
> docs: wrong import fixed

- .changeset/mean-items-act.md
- packages/machines/tags-input/src/tags-input.connect.ts
Closes #804 
Currently, Tags Input allows keys during the compositions in `onKeyDown` event.
This behavior cause the above bug since it is not possible to distinguish between keys entered by the user and keys for IME combinations.
So this PR fixes it by ignoring `onKeyDown` events whose `isComposing` property is true.
Allow keys during the compositions in `onKeyDown` event.
Ignore keys during the compositions in `onKeyDown` event.
No
None
> fix(tags-input): ignore key during composition in `onKeyDown` event

- .changeset/large-books-own.md
- .xstate/combobox.js
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/combobox/src/combobox.machine.ts
- packages/machines/combobox/src/combobox.types.ts
- packages/utilities/dom-event/src/assertion.ts
- shared/src/controls.ts
- website/data/components/combobox.mdx
Closes #604
1. add closeOnSelect setting to combobox
2. document it
3. fix: do not select and close Combobox on context menu click
1. There **is no** closeOnSelect flag.
2. The onClose handler **does not** get called when combobox gets closed (by enter or click) and is in `suggesting` state.
3. Right clicking (or on Mac left clicking with ctrl key pressed) on the option **is getting treated as a option selection** (but only the second right click selects the option).
1. There **is a** closeOnSelect flag which allows to block closing the menu.
2. The onClose handler **is** getting called when combobox gets closed (by enter or click) and is in `suggesting` state.
3. Right clicking (or on Mac left clicking with ctrl key pressed) on the option **does not trigger option selection**.
Yes, if …
> feat(combobox) add closeOnSelect and overall combobox improvements

- .changeset/perfect-games-train.md
- packages/machines/range-slider/src/range-slider.connect.ts
- packages/machines/slider/src/slider.connect.ts
Closes # 
Fixes an issue where thumb drag works and onChange occurs when <Slider/> and <RangeSlider /> are `disabled` in the current `@ark-ui/react` version 0.14.0 and `@zag-js/slider`, `@zag-js/range-slider` version 0.19.1.
Add a guard for `isInteractive` to `onPointerDown` to prevent it from falling into a dragging state.
You can see demo in [here](https://stackblitz.com/edit/stackblitz-starters-kjjwdw?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter)
cc. @malangcat
> fix(slider, range-slider): prevent thumb drag when disabled true

- .changeset/cold-coins-tie.md
- e2e/pagination.e2e.ts
- examples/solid-ts/src/pages/pagination.tsx
- packages/machines/pagination/src/pagination.machine.ts
Closes #867
It fixes the aforementioned bug
onChange is not getting invoked in setPage action
onChange is getting invoked in setPage action
No
> fix(pagination): add onChange to page buttons

- .changeset/five-moose-sin.md
- packages/machines/pagination/src/pagination.connect.ts
- packages/machines/pagination/src/pagination.utils.ts
- packages/machines/pagination/tests/pagination.utils.test-cases.ts
- packages/machines/pagination/tests/pagination.utils.test.ts
My colleague found a bug so I fixed it.
Apart from that, I add ~50 test cases for pagination and refactor the getRange function.
1. In some cases, no pagination numbers are returned (in this case, page 4):
https://github.com/chakra-ui/zag/assets/17103865/5b84dede-67d9-46ac-83f9-f738e601e5fc
Data from the video: 
```js
{
count: 8,
page: 4,
pageSize: 1,
siblingCount: 2,
}
```
1. Bug fixed:
https://github.com/chakra-ui/zag/assets/17103865/1d5bcd6b-25ff-408c-bd9a-6272648150da
No
> fix(pagination): fix edge cases, refactor and simplify code, add tests

- .changeset/heavy-jars-enjoy.md
- packages/utilities/focus-visible/src/index.ts
Closes [#8000](https://github.com/chakra-ui/chakra-ui/issues/8000)
Fix for inconsistent checkbox focus ring behaviour when a checkbox is descendant of an element with `tabindex` attribute. The problem is that the browser fires an extra window `focus` event when the user clicks inside an element which has `tabindex` property. This event needs to be ignored in order to ensure consistent focus ring behaviour.
Focus-visible ring appears on mouse click if checkbox is descendant of an element with `tabindex` attribute.
Focus-visible ring does not appear on mouse click if checkbox is descendant of an element with `tabindex` attribute.
No
> fix: focus-visible

- .changeset/new-monkeys-watch.md
- packages/machines/editable/src/editable.machine.ts
There is currently an issue in `@zag-js/editable` 0.21.0 where passing an object with a state value of `useState` and using the `<Editable />` component in controlled form does not control the value as desired.
You can see a demo below.
(Currently, the logic is set up so that the value is fixed at 10000, but you can see that any value above 10000 will be input).
- [demo](https://stackblitz.com/edit/stackblitz-starters-m4rdhb?file=src%2FApp.tsx,src%2Fstyle.css)
To fix this, modify the code for `zag` and `ark`.
In `zag`, we'll add logic to synchronize if the externally input value is different from the internal value.
In `ark`, we apply `flushSync` to `onChange`.
- [ark PR](https://github.com/chakra-ui/ark/pull/1441)
If there is a better form, please let me know.
cc. @malangcat
> fix(react): `<Editable />` sync internal value and external value

- .changeset/unlucky-carrots-punch.md
- .xstate/file-upload.js
- packages/docs/api.json
- packages/machines/file-upload/src/file-upload.machine.ts
- packages/machines/file-upload/src/file-upload.types.ts
According to Павлюткин Артём from Discord (https://discord.com/channels/964648323304808488/964648323304808496/1151315874020605972):
> Hi, I have a problem. Through the Safari browser, I click on the "Download" button for the first time, a window appears to download the file. If you press the button again, nothing happens.
>I tried it on the official website from the Safari browser.
>The problem is only in the mobile browser on the iPhone.
I also discovered that the problem also occurs on Firefox and Safari on macOS and I confirm that it occurs on Safari on iOS.
1. User gets stuck in the open state on the majority of the browsers, with no way to escape the open state.
2. There is no possibility to drag and drop files while dropzone is focused.
3. There is unused DROPZONE.ENTER transition. …
> fix(file-upload): fix reopening the system file picker on browsers other than Chrome

- e2e/tags-input.e2e.ts
Closes # 
- Add test for editing tag with mouse double click
- No new behavior, I just add test a stuff
- No new behavior, I just add test a stuff
No
> feat(tags-input): add test for editing tag with mouse double click

- .xstate/file-upload.js
- packages/machines/file-upload/src/file-upload.connect.ts
- packages/machines/file-upload/src/file-upload.machine.ts
Closes # 
This fixes the setFiles and clearFiles API's of the file upload machine.
Nothing happens when called
Files can be modified using setFiles(files) and all files can be cleared using clearFiles()
> fix: file upload setFiles and clearFiles methods

- .changeset/friendly-plums-serve.md
- packages/machines/radio-group/src/radio-group.connect.ts
This PR changes the indicator when it has a border (in this example `border: "5px solid red"`).
After resetting the state, when the value is `null`, the indicator remains visible. It sets its width/height to zero, but it's not sufficient to fully hide it - the border remains visible.
When the value is `null`, the indicator gets `display: none` in inline CSS and thus disappears.
No
Empty string gets treated as a value and does not hide the indicator, since I assume that the only empty value of the radio is null.
Another solution would be to use some custom `data-state="visible/hidden"` on indicator but I think that the solution with `display=none` is sufficient. It still lets the user to use any `display: <value>` since the `display: none;` from inline styles has higher specificity than …
> fix(radio-group): hide indicator when the value is null 

- website/data/snippets/vue-sfc/tabs/usage.mdx
- website/data/snippets/vue-sfc/tags-input/usage.mdx
Wrong data binding of Tabs and Tags Input Components in Vue (SFC)
- https://zagjs.com/components/react/tabs
- https://zagjs.com/components/react/tags-input
- Tabs have data binding is `{item.label}` and `{item.content}`
- Tags Input have data binding is `{value}`
- Tabs have data binding is `{{ item.label }}` and `{{ item.content }}`
- Tags Input have data binding is `{{ value }}`
> docs: Update code snippets (vue sfc) tags and tags input components

- .changeset/wet-plants-flash.md
- packages/core/src/merge-props.ts
fix a typeerror using the mergeProps function. 
```
merge-props.ts:9 Uncaught TypeError: str.trim is not a function
at merge-props.ts:9:24
at Array.map (<anonymous>)
at clsx (merge-props.ts:9:6)
at mergeProps (merge-props.ts:30:23)
```
The nullish coalescing check is applied to 'str', but 'trim' lacks such protection.
nullish coalescing for trim as well
> fix: typeerror when clsx str is undefined

- .changeset/ten-candles-pretend.md
- packages/machines/combobox/src/combobox.machine.ts
When setting `inputBehavior` to `autocomplete` oninVue version, nothing happens to input value when you move through items. Same behavior works for React and Solid versions.
I’ve wrappend DOM mutation inside `requestAnimationFrame` call, but I don’t know if that’s correct way to approach these issues.
Setting `inputBehavior` to `autocomplete` should update input value to highlighted item. Works for React and Solid, but not for Vue.
Setting `inputBehavior` to `autocomplete` should update input value to highlighted item on all frameworks.
This also makes Playwright test pass, and that was the only one not passing for combobox.
Not breaking change.
N/A
> fix(combobox): autocomplete not working in vue version

- .changeset/chilled-bees-switch.md
- .xstate/presence.js
- packages/machines/presence/src/presence.machine.ts
Fixes chakra-ui/ark#1627 
There is a missing invoke for `onExitComplete`
Fires `onExitComplete` invoke properly
No
> fix(presence): missing invoke on exit complete

- packages/docs/api.json
- packages/utilities/interact-outside/src/index.ts
`combobox` everywhere is somewhat misleading
> docs: fix types description

- website/data/snippets/vue-sfc/select/usage.mdx
Missing `selectData` and `collection` property in select: https://zagjs.com/components/react/select
In usage of select, missing `selectData` and `collection` property
Adding `selectData` and `collection` property for select
No
> docs: Update missing selectData and collection property in select (vue-sfc)

- website/data/snippets/vue-sfc/color-picker/usage.mdx
- website/data/snippets/vue-sfc/color-picker/with-channel-inputs.mdx
- website/data/snippets/vue-sfc/color-picker/with-eye-dropper.mdx
- website/data/snippets/vue-sfc/color-picker/with-preview.mdx
- website/data/snippets/vue-sfc/color-picker/with-swatches.mdx
Add code snippet for color picker (vue-sfc): https://zagjs.com/components/vue-sfc/color-picker
- Color Picker (vue-sfc): `Snippet not found :(`
- Color Picker (vue-sfc): Adding snippet for usage, showing color presets, controlling individual color channel, showing a color preview and adding a eyedropper.
No
> docs: Add code snippet for color picker (vue-sfc)

- examples/next-ts/pages/tooltip.tsx
- website/data/overview/installation.mdx
Closes # 
I've updated [the Getting Started page](https://zagjs.com/overview/installation) because it doesn't work.
The Getting Started page uses Toggle as an example, but it has been removed at https://github.com/chakra-ui/zag/commit/942db6caf9f699d6af56929c835b10ae80cfbc85, and its last release (v0.19.1) doesn't work with the latest version of Zag.
https://codesandbox.io/p/devbox/romantic-firefly-dhv3dk?file=%2Fsrc%2FToggle.tsx%3A10%2C1
I've updated the examples with Tooltip, which is as simple as Toggle.
> docs: replace Getting Started examples with Tooltip

- website/data/snippets/vue-jsx/color-picker/usage.mdx
- website/data/snippets/vue-jsx/color-picker/with-channel-inputs.mdx
- website/data/snippets/vue-jsx/color-picker/with-eye-dropper.mdx
- website/data/snippets/vue-jsx/color-picker/with-preview.mdx
- website/data/snippets/vue-jsx/color-picker/with-swatches.mdx
Add code snippet for color picker (vue-jsx): https://zagjs.com/components/vue-sfc/color-picker
- Color picker of Vue 3 (JSX): `Snippet not found :(`
- Color picker of Vue 3 (JSX): Adding snippet for usage, showing color presets, controlling individual color channel, showing a color preview and adding a eyedropper.
No
> docs:  Add code snippet for color picker (vue-jsx)

- README.md
- package.json
Closes # 
This PR provides contributors with an intuitive way to run the website in local environments.
zag has the `pnpm website` script, but we have to add the `dev` command to run the website.
```
pnpm website dev
```
If we run the run the npm script (`website`) without the command (`dev`), we would see the following error.
```
> pnpm --filter=./website
 ERROR  Unknown option: 'recursive'
For help, run: pnpm help recursive
 ELIFECYCLE  Command failed with exit code 1.
```
I'd like to add the `start-website` script, which is a command to run the website, as an explicit way to run the website.
There are already ' start-***` commends to run examples, so I've followed the convention.
> chore: add start-website as an npm script

- packages/utilities/dom-query/src/get-by-text.ts
Following this PR that I submitted for Ark: https://github.com/chakra-ui/ark/pull/1795
I suggest to trim the text in the get-by-text utility of the dom-query, allowing to find an item, event if it contains extra spaces in its text.
> fix (dom-query): trim text to ensure finding an item by text

- examples/next-app/app/page.tsx
- examples/next-app/app/select-search-params/page.tsx
Use a longer list of items in the select collection of the nextjs with search params example.
With a collection with fewer items, it doesn't replicate this issue: https://github.com/chakra-ui/zag/discussions/1088
With a longer list of items in collection it reproduces the bug in the issu.
No
https://github.com/chakra-ui/zag/assets/53458125/0480b610-e51c-4c39-8661-8cd6eab23891
> chore: use selectData from shared in next example

- website/data/components/switch.mdx
Fixed typos for the `onCheckedChange` option on the `listening for changes` example section of the Switch component.
The example used `onCheckChange` as the name for the option.
This has now been changed to `onCheckedChange`.
No
N/A
> docs: fix typo with listening for changes example for switch component

- packages/utilities/collection/src/collection.ts
Fixed the difference `items` types in  `Collection` constructor and `setItems`
In the `Collection` constructor, the `items` type of  `CollectionOptions` is ` T[] | readonly T[]`, but in `setItems` function is `T[]`
update `setItem` function type from `(items: T[]) => Collection<T>` to `(items: T[] | readonly T[]) => Collection<T>`
> fix: add readonly to collection setItems

- .xstate/presence.js
- packages/machines/presence/src/presence.machine.ts
Closes # 
fixed not set initial context for presence
the usecase: 
```ts
const [state, send] = useMachine(
presence.machine({
...context.value,
onExitComplete: () => {
emit('exit-complete')
},
}),
// the below context don't include onExitComplete anymore
{ context },
)
```
if i passed `onExitComplete` as initial context to useMachine, the onExitComplete won't call correctly
set initial context for presence
> fix(presence): set initial context

- .changeset/green-bananas-ring.md
- packages/machines/combobox/src/combobox.machine.ts
Closes #1133 
Add the input element to the exclude list of the `trackDismissableElement` function so it won't be considered as an "outside interaction" anymore.
When clicking on the input element while the menu is open, it closes the menu and it won't open again until we click outside the component and focus the input again.
Also, if the `openOnclick` property is set to `true`, and when clicking on the input element when the menu is open, it closes the menu before opens it right away.
When clicking on the input element while the menu is open does not close it anymore.
No
> fix(combobox): fix input click when menu is open

- website/data/snippets/react/combobox/usage.mdx
Closes #1145 
Solves issue #1145 
When the snippet is used, the arrow down or up does not work when the combobox list is filtered.
When the snippet is used, the arrow down/up hightlight the first item of the filtered list.
💣 Is this a breaking change (No)
> [React] docs: fix combobox `items` in the instantiation of collections (#1145)

- website/data/snippets/solid/avatar/usage.mdx
Closes # No issue was created for this
The example usage for Avatar on SolidJS doesn't work, I opened a discussion about it with more details because I thought it was a mistake from my side.
https://github.com/chakra-ui/zag/discussions/1157
We should check that the issue doesn't occur in other examples, maybe when I will have time I will do it myself.
Please see:
https://github.com/chakra-ui/zag/discussions/1157
Now using `createMemo` (although a derived signal might work as well) the example uses best practice as well as just works.
No.
> Fix Avatar solid usage example

- .changeset/wet-boats-brush.md
- packages/machines/pin-input/src/pin-input.connect.ts
- packages/machines/pin-input/src/pin-input.machine.ts
When pasting in the pin input after it has been filled, the copied text will sometimes fill a single input, where it should be limited to a single character. This is mostly a visual bug, as the state value is still 'correct' (the first char is used).
Also fixes some inconsistency with pasting a value after being filled. It should now paste the copied text from the current focused input onward, without appending the focused input's value.
https://github.com/chakra-ui/zag/assets/13904763/a2e23a4b-bc25-4a20-a44b-0cc124bf72ce
https://github.com/chakra-ui/zag/assets/13904763/a00246f1-b7e5-47a9-b09d-10f97ee4ac30
https://github.com/chakra-ui/zag/assets/13904763/608f8bfd-4a98-44a3-908d-d65f1b869aa9
No
> fix: pin input paste behaviour

- .changeset/famous-lobsters-yawn.md
- packages/machines/select/src/select.connect.ts
Closes # 
> this will enable styling of indicator when building custom select component with chakra-ui and applying visual styles trough theme via: _disabled, _readOnly, _invalid props
> data and aria attributes are currently not visible on indicator atom
> now those props are applied as compared to triggerProps
No
indicatorProps are not shown in documentation, i saw that ark-ui uses it in its select implementation.
> feat: add data-disabled, data-invalid, aria-invalid, data-readonly to indicatorProps for Select

- .changeset/wild-drinks-pretend.md
- packages/machines/select/src/select.connect.ts
> `aria-activedecesendant` on select machine now correctly references the chosen value by the element id
> Just the value of an item is used, which is not accessible since it does not reference the right element
> Now uses `dom.getItemId()`, same as the item elements
no
> fix(machines): select uses the correct `id` for `aria-activedecesendant` field

- .changeset/spicy-experts-wonder.md
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/combobox/src/combobox.types.ts
- packages/machines/select/src/select.types.ts
Closes #1226
- Add collection api to Combobox's api. (Like Select: [commit](https://github.com/chakra-ui/zag/commit/3f7ea3936cb86231a105f5d919aff44ddaea60e1#diff-da0ad57d3ce06be4a0bd6f75c2fa4e7eb97a8b0a25feebe0363322f937093ca6))
- Fix typos in Select types (Combobox to Select)
`collection` api is not provided by Combobox.
`collection` api is provided.
No
> feat(machines): add `collection` api to Combobox

- .changeset/selfish-masks-sleep.md
- packages/machines/tooltip/src/tooltip.connect.ts
Closes #1247
Tooltip that has `disabled` props is unintentionally displayed when hovering and clicking the target.
like this (emulate with zag-js React dev)
https://github.com/chakra-ui/zag/assets/38889285/c603b2a3-4898-4553-8871-7a38607db17b
like this (emulate with zag-js React dev)
https://github.com/chakra-ui/zag/assets/38889285/70e187e9-39c3-4aab-b8af-96ce575d6324
No
> fix(machines): add disabled check in tooltip trigger eventHandler

- .changeset/nice-maps-type.md
- packages/machines/date-picker/src/date-picker.connect.ts
> Fix the aria labels of the next and previous triggers in the date picker.
> In the date picker, the aria labels of the next and previous triggers are inverted.
> Put them in the right order.
> fix(date-picker): next and previous aria labels

- website/components/machines/switch.tsx
- website/components/showcase.tsx
- website/data/components/switch.mdx
https://github.com/chakra-ui/zag/pull/1304#issuecomment-1971935771
Based on this comment, I have removed the relevant sections from the document.
No
Ref: https://github.com/chakra-ui/zag/pull/1304
> docs(website): remove read only section from switch

- .vscode/extensions.json
Remove the TypeScript Vue Plugin VSCode extension from project recommendations, as this is now deprecated.
> chore(.vscode): remove vue ts extension from recommendations

- examples/nuxt-ts/package.json
- examples/vue-ts/package.json
- pnpm-lock.yaml
Bumps the `vue` dep for the Nuxt and Vue TS examples to latest, to match the version in `@zag-js/vue`, preventing unexpected Type errors in the example files.
> chore(examples): bump vue dep to latest

- examples/next-ts/pages/clipboard.tsx
- examples/nuxt-ts/pages/clipboard.vue
- examples/solid-ts/src/pages/clipboard.tsx
- examples/vue-ts/src/pages/clipboard.tsx
- website/data/snippets/react/clipboard/usage.mdx
- website/data/snippets/solid/clipboard/usage.mdx
- website/data/snippets/vue-jsx/clipboard/usage.mdx
- website/data/snippets/vue-sfc/carousel/usage.mdx
- website/data/snippets/vue-sfc/clipboard/usage.mdx
> Update value clipboard and variable in carousel
Variable `image` doesn't exist in loop sfc `v-for="(item, index) in items"`
Value of clipboard: `https://github/com/chakra-ui/zag`
`v-for="(image, index) in items"`
`https://github.com/chakra-ui/zag`
No
> docs: clipboard and carousel

- .changeset/giant-ties-notice.md
- examples/next-ts/pages/tabs.tsx
- examples/nuxt-ts/pages/tabs.vue
- examples/solid-ts/src/pages/tabs.tsx
- examples/vue-ts/src/pages/tabs.tsx
- packages/docs/data/api.json
- packages/machines/tabs/src/tabs.connect.ts
- packages/machines/tabs/src/tabs.dom.ts
- packages/machines/tabs/src/tabs.types.ts
- shared/src/style.css
- website/components/machines/tabs.tsx
- website/components/mdx-components.tsx
- website/components/mutli-framework.tsx
- website/data/components/tabs.mdx
- website/data/snippets/react/tabs/usage.mdx
- website/data/snippets/react/tabs/with-indicator.mdx
- website/data/snippets/solid/tabs/usage.mdx
- website/data/snippets/solid/tabs/with-indicator.mdx
- website/data/snippets/vue-jsx/tabs/usage.mdx
- website/data/snippets/vue-jsx/tabs/with-indicator.mdx
- website/data/snippets/vue-sfc/tabs/usage.mdx
- website/data/snippets/vue-sfc/tabs/with-indicator.mdx
Tabs: Rename `tablist` part to `list` to match naming convention
> refactor(tabs): rename tablist to list

- .changeset/stale-waves-kiss.md
- examples/next-ts/pages/combobox.tsx
- examples/nuxt-ts/pages/combobox.vue
- examples/solid-ts/src/pages/combobox.tsx
- examples/vue-ts/src/pages/combobox.tsx
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/combobox/src/combobox.machine.ts
Closes #1320
Updates the rendering on page load of a "clear" button that uses `clearTriggerProps` where the combobox is provide a default value.
When a user provides an initial `value` to the machine's context, it does not cause the button using `clearTriggerProps` to be visible on the page.
In `clearTriggerProps`, have the `hidden` attribute be checked with the `value` context instead of `inputValue`
No
> fix(machine/combobox): use `value` context with `clearTriggerProps` hidden check

- website/components/mdx-components.tsx
- website/data/components/toast.mdx
Builds a custom table component for the toast doc page.
The `remark-gfm` plugin is currently not installed, so the table markdown provided in the [Setting Custom Duration](https://zagjs.com/components/react/toast#setting-custom-duration) section does not render correctly.
As this is the only table markdown for the entire site, it is a better choice to create a custom component for this instance than to try and add the plugin (which does not work [for another reason](https://github.com/remarkjs/remark-gfm/issues/57)). 
This custom component is also made to be reusable if needed, as a two-column only table.
> docs(website/mdx-components): create table component for toast page

- .changeset/lemon-insects-remember.md
- packages/machines/progress/src/progress.connect.ts
Closes https://github.com/chakra-ui/zag/issues/1361
My solution on Issue was not 100% correct since the progress didnt start at 12 o' clock.
i used this blogpost as an idea: [Blog](https://nikitahl.com/svg-circle-progress#:~:text=We%20need%20to%20set%20stroke%2Ddasharray%20property%20value%20to%20be%20equal%20to%20the%20circumference%20of%20our%20circle%2C%20this%20way%20it%20will%20fill%20up%20the%20whole%20circle%20and%20be%20equal%20to%20100%25.%20Next%2C%20we%20need%20to%20set%20stroke%2Ddashoffset%20to%20move%20the%20progress%20back%20(offset)%20as%20if%20we%E2%80%99re%20subtracting%20from%20our%20progress)
Thanks @isBatak
No
> fix: circular progress circle diameter

- .changeset/spicy-carpets-tell.md
- packages/utilities/tabbable/src/focusable.ts
- packages/utilities/tabbable/src/tabbable.ts
~~Closes #~~
This PR simply fixes some TypeScript types from the package `@zag-js/tabbable`, by explicitly adding returned types. 
The current `.d.ts` file in [`@zag-js/tabbable@0.41.0`](https://unpkg.com/browse/@zag-js/tabbable@0.41.0/dist/index.d.ts) declares that some API returns `HTMLElement`. 
```ts
/**
* Returns the first focusable element within the element
*/
declare function getFirstTabbable(...): HTMLElement;
```
But they should return `HTMLElement | null`. 
```ts
/**
* Returns the first focusable element within the element
*/
declare function getFirstTabbable(...): HTMLElement | null;
```
No
N/A
> fix(tabbable): correct some returned types

- .changeset/clean-clouds-wink.md
- packages/utilities/collection/src/collection.ts
Closes #1433
use coping method for sorting in collection util.
If implemented like this, original array is also sorted.
```tsx
sort = (values: string[]): string[] => {
return values.sort(this.sortFn)
}
```
use the copying version of the sort() method: [`Array.prototype.toSorted`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted) 
No, values will be not sorted but it is expected behavior
This fix affects Select and Combobox machine
- in Select
https://github.com/chakra-ui/zag/blob/67f5faa024ffd9e0ea594508d61faf05ee86a5be/packages/machines/select/src/select.machine.ts#L495-L507
- in Combobox
https://github.com/chakra-ui/zag/blob/67f5faa024ffd9e0ea594508d61faf05ee86a5be/packages/machines/combobox/src/combobox.machine.ts#L598-L601
> fix(collection): fix collection sort function using by copying method

- website/data/overview/programmatic-control.mdx
- website/data/overview/styling.mdx
Thanks for creating such a cool project like Zag.js. I found the documentation incredibly engaging and read through it all at once. During my reading, I noticed a typo, which I would like to report.
> docs: fix typo

- .changeset/green-masks-admire.md
- packages/frameworks/preact/src/use-snapshot.ts
- packages/frameworks/react/src/use-snapshot.ts
- packages/store/src/global.ts
- packages/store/src/index.ts
- packages/store/src/proxy.ts
Fix an issue where multiple versions of @zag-js/store could lead to "proxy state is not iterable" errors.
> fix: use singleton globals

- .changeset/three-beers-clap.md
- .xstate/collapsible.js
- .xstate/presence.js
- packages/machines/collapsible/src/collapsible.connect.ts
- packages/machines/collapsible/src/collapsible.machine.ts
- packages/machines/collapsible/src/collapsible.types.ts
- packages/machines/presence/src/presence.machine.ts
- shared/src/css/collapsible.css
- starters/react/app/accordion/collapsible/page.tsx
- starters/react/app/collapsible/controlled/page.tsx
- starters/react/components/accordion.tsx
Closes #1396
Fix the issue where the initial height animation can sometimes run.
> refactor: collapsible machine

- website/data/components/color-picker.mdx
- website/data/snippets/react/combobox/usage.mdx
- website/data/snippets/react/dialog/usage.mdx
- website/data/snippets/react/editable/custom-controls.mdx
- website/data/snippets/solid/combobox/usage.mdx
- website/data/snippets/solid/dialog/usage.mdx
- website/data/snippets/solid/editable/custom-controls.mdx
- website/data/snippets/vue-jsx/combobox/usage.mdx
- website/data/snippets/vue-jsx/dialog/usage.mdx
- website/data/snippets/vue-jsx/editable/custom-controls.mdx
- website/data/snippets/vue-sfc/combobox/usage.mdx
- website/data/snippets/vue-sfc/dialog/usage.mdx
- website/data/snippets/vue-sfc/editable/custom-controls.mdx
Fix typos and update outdated API usages in the documentation. Specifically:
- [ColorPicker](https://zagjs.com/components/react/color-picker): `combobox` -> `colorPicker`
- [Combobox](https://zagjs.com/components/react/combobox): `onInputValueChange({ value })` -> `onInputValueChange({ inputValue })`
- [Dialog](https://zagjs.com/components/react/dialog): `api.isOpen` -> `api.open`
- [Editable](https://zagjs.com/components/react/editable): `api.isEditing` -> `api.editing`
> docs: fix typos and update outdated API usages

- examples/nuxt-ts/pages/signature-pad.vue
- website/data/snippets/vue-sfc/presence/usage.mdx
- website/data/snippets/vue-sfc/signature-pad/usage.mdx
> Update variable for presence and key for signature pad in vue-sfc
-  `present`, `apiRef` is not defined in presence code snippet of vue-sfc
- `<path v-for="path of api.paths" key="{i}" v-bind="api.getSegmentPathProps({ path })" />"` is not valid in signature code snippet of vue-sfc
- Presence: update variable in defineProps
```js
const {present, unmountOnExit } = defineProps<{
present: boolean
unmountOnExit?: boolean
}>()
```
- Signature: update key by index
```js
<path v-for="(path, i) of api.paths" :key="i" v-bind="api.getSegmentPathProps({ path })" />
```
No
> docs: presence and signature pad in vue-sfc

- website/data/overview/installation.mdx
- website/data/snippets/react/tooltip/usage.mdx
- website/data/snippets/solid/tooltip/usage.mdx
- website/data/snippets/vue-jsx/tooltip/usage.mdx
- website/data/snippets/vue-sfc/tooltip/usage.mdx
> Using `api.open` instead of `api.isOpen` from `@zag-js/tooltip`
Using `api.isOpen` in code snippets of tooltip
Using `api.open` in code snippets of tooltip
No
> docs: tooltip

- .changeset/little-crews-reply.md
- packages/utilities/collection/src/collection.ts
Ensure that collection with attributes that changes (e.g. disabled) should be considered as changed.
When the items of a collection are updated with only a state change, the collection is considered as equal (as the values are the same).
When the items of a collection are updated with only a state change, the collection should be considered as changed, as of now, the disabled attribute changed IS considered as a change for the collection.
No
> fix(collection): ensure collection are considered different when disabled change

- website/data/snippets/react/hover-card/usage.mdx
- website/data/snippets/solid/hover-card/usage.mdx
- website/data/snippets/vue-jsx/hover-card/usage.mdx
- website/data/snippets/vue-sfc/hover-card/usage.mdx
> Using `api.open` instead of `api.isOpen` from `@zag-js/hover-card`
Using `api.isOpen` in code snippets of hover card
Using `api.open` in code snippets of hover card
No
> docs: using open instead of isOpen from @zag-js/hover-card

- packages/machines/clipboard/src/clipboard.dom.ts
Closes # 
Clipboard API is never used because the condition is wrong.
See above
Browser support is correctly checked so `writeText` of Clipboard API is called if supported
No
You can reproduce this here
https://codesandbox.io/p/sandbox/determined-neco-9ktp4x?file=%2Fsrc%2FApp.tsx
> fix(clipboard): correct condition to use clipboard API

- website/data/snippets/vue-sfc/tabs/usage.mdx
- website/data/snippets/vue-sfc/tabs/with-indicator.mdx
> Fix key in code snippet of vue-sfc tabs
`key="{item.value}"`
`:key="item.value"`
No
> docs: tabs

- website/data/snippets/react/checkbox/usage.mdx
- website/data/snippets/react/switch/usage.mdx
- website/data/snippets/solid/switch/usage.mdx
- website/data/snippets/vue-jsx/checkbox/usage.mdx
- website/data/snippets/vue-jsx/switch/usage.mdx
- website/data/snippets/vue-sfc/avatar/usage.mdx
- website/data/snippets/vue-sfc/checkbox/usage.mdx
- website/data/snippets/vue-sfc/switch/usage.mdx
> Fix checked for api of checkbox and switch
- Avatar using key is `src="{src}"`
- Checkbox using `api.isChecked`
- Switch using `api.isChecked`
- Avatar using key is `:src="src"`
- Checkbox using `api.checked`
- Switch using `api.checked`
No
> docs: checkbox and switch

- .xstate/tour.js
- examples/next-ts/pages/tour.tsx
- examples/solid-ts/src/pages/tour.tsx
- examples/svelte-ts/src/routes/tour.svelte
- examples/vue-ts/src/pages/tour.tsx
- packages/docs/data/api.json
- packages/machines/tour/src/tour.connect.ts
- packages/machines/tour/src/tour.machine.ts
- packages/machines/tour/src/tour.types.ts
- website/data/overview/composition.mdx
- website/data/snippets/react/clipboard/usage.mdx
- website/data/snippets/react/rating-group/usage.mdx
- website/data/snippets/solid/checkbox/usage.mdx
- website/data/snippets/solid/clipboard/usage.mdx
- website/data/snippets/solid/rating-group/usage.mdx
- website/data/snippets/vue-jsx/clipboard/usage.mdx
- website/data/snippets/vue-jsx/rating-group/usage.mdx
- website/data/snippets/vue-sfc/clipboard/usage.mdx
- website/data/snippets/vue-sfc/rating-group/usage.mdx
> chore: adhere boolean api

- .changeset/sour-books-act.md
- packages/machines/popover/src/popover.machine.ts
Closes #1542
As described on #1542, the popover component will reset scroll position when it is opened.
I found `{ preventScroll: true }` parameter of `HTMLElement.focus()` is missing after 0.50.0, which is set before 0.49.0.
https://github.com/chakra-ui/zag/blob/%40zag-js/popover%400.49.0/packages/machines/popover/src/popover.machine.ts#L228
https://github.com/chakra-ui/zag/blob/%40zag-js/popover%400.50.0/packages/machines/popover/src/popover.machine.ts#L230
The popover content does not look place right position just after opening, `setInitialFocus` will cause this timing, so I think we still need `{ preventScroll: true }` parameter.
The popover component will reset scroll position when it is opened.
The popover component DOES NOT reset scroll position when it is opened.
No
> fix: avoid reset scroll position on opening popover

- .changeset/seven-buttons-drum.md
- packages/docs/data/data-attr.json
- packages/machines/combobox/src/combobox.connect.ts
- packages/machines/select/src/select.connect.ts
There's no way to know if an item is selected when directly targeting ItemText. This fixes that by exposing `data-state` for ItemText.
No
A bunch of stuff is generated when adding new data attributes. I cherry-picked the two relevant ones and discarded the rest.
> fix: expose data-state on item-text for combobox and select

- .changeset/early-hairs-do.md
- packages/docs/data/data-attr.json
- packages/machines/combobox/src/combobox.connect.ts
Expose (missing) `data-placement` on Combobox's content.
No.
> fix: expose content placement on combobox

- .changeset/wet-books-speak.md
- packages/machines/combobox/src/combobox.machine.ts
Closes #1642 
The input value won't change even if `selectionBehavior` is replace 
https://gyazo.com/6e077501a3eefef879d00e4073d32e79
No
> fix(combobox): fix a combobox select bug

- .changeset/metal-falcons-boil.md
- packages/store/src/proxy.ts
Related to https://github.com/chakra-ui/ark/discussions/2609
Avoid calling `process` at top level to avoid crash in web environment (where process is not defined)
> refactor: change top-level process call in proxy.ts

- .changeset/silver-ducks-brush.md
- packages/utilities/dom-query/src/is.ts
~~Closes #~~ 
This PR includes two improvements for `isHTMLElement()` functions etc.
1. Ensure they work on Node.js, where global `Node` is not available. 
2. Check whether the past argument is a valid object. This ensures that passing a `null` or `undefined` won't throw errors. The typescript signature for past `ev` is `any` so it's better to support `null` and `undefined` etc.
```
$ echo "require('@zag-js/dom-query').isHTMLElement({});" | node
var isHTMLElement = (v) => typeof v === "object" && v?.nodeType === Node.ELEMENT_NODE && typeof v?.nodeName === "string";
^
ReferenceError: Node is not defined
```
```
$ echo "require('@zag-js/dom-query').isNode(null);" | node
var isNode = (el) => el.nodeType …
```
> fix: improve is* checkers compatibility

- .changeset/ninety-geese-repair.md
- packages/machines/time-picker/src/time-picker.connect.ts
- packages/machines/time-picker/src/time-picker.machine.ts
- packages/machines/time-picker/src/time-picker.utils.ts
If the locale corresponds to a 24 hours format, and the user selects an hour after 11, the cell would not be selected.
Fix by making `getHourPeriod` return `null` if the locale corresponds to a 24 hours format.
No
> fix(time-picker): wrong selected hour on 24 hours format

- website/data/overview/whats-a-machine.mdx
Closes #1749 
This pull request changes nothing but a `.mdx` file which is relevant to `whats-a-machine` link.
> docs: use getButtonProps instead of buttonProps

- .changeset/many-papayas-clap.md
- examples/next-ts/pages/avatar.tsx
- packages/machines/avatar/src/avatar.machine.ts
Checking the NodeType for errors caused by having a TextNode instead of an HTMLElement in removedNodes.
If the name of the Avatar is an empty string, this type error occurs.
No error
No
> fix(avatar): check removed avatar node type

- .changeset/spicy-mugs-run.md
- packages/machines/combobox/src/combobox.machine.ts
Closes # 
In Combobox, when we want to display something like `no option` when filtering by input, an unintended highilghtedValue is kept in the internal state.
This would cause an empty item (like value=‘something’, item=null) to be selected, so this issue has been fixed.
https://github.com/user-attachments/assets/50df8bc9-97c7-4a77-83d1-6756b06620bd
When items changed (in other word, to change the children node), forced update the highlighted value.
This ensures that the highlight value is not an unintended, 
because the value of `ctx.collection.firstValue` will be null if items is not present and null will be forced set.
https://github.com/user-attachments/assets/6af1a738-4948-49bf-9327-07ee5bd9e8a7
I thought about preventing value changes when item=null, but I thought that the problem …
> fix(combobox): highlight values remain when items changed

- website/data/overview/composition.mdx
The `triggerProps` variable was created but not used.
No.
> Fix typo in composition.mdx

- CHANGELOG.md
- packages/machines/tags-input/CHANGELOG.md
fix typo in tags input changelog
> chore: fix typo in tags input changelog

- examples/nuxt-ts/components/TreeNode.vue
- examples/nuxt-ts/pages/tour.vue
- website/data/snippets/vue/tour/usage.mdx
- website/data/snippets/vue/tree-view/usage.mdx
> update snippets for tour and tree view
- `api.step` is possibly 'null' in tour
- `Toolbar` in tree view is unused
- update `api.step?` in `tour.vue` and `steps` data missing in code snippet
- remove `Toolbar` and update `import type { Api } from "@zag-js/tree-view"` for `TreeNode.vue`
No
> docs: update snippets for tour and tree view

- packages/utilities/aria-hidden/src/index.ts
📝 Description
This PR updates the ariaHidden function to handle cases where the targets array is empty.
⛳️ Current behavior (updates)
The hideOthers function does not handle cases where the array is empty, which results in a type error.
🚀 New behavior
I added a conditional check to handle cases where the array is empty, just like it was done previously.
💣 Is this a breaking change (Yes/No):
No
📝 Additional Information
> fix(aria-hidden): skip empty elements hide

- .changeset/light-tomatoes-trade.md
- packages/frameworks/svelte/src/index.ts
- packages/frameworks/svelte/src/merge-props.ts
Fix style merging in svelte `mergeProps`
closes #2046
> fix(svelte): merge-props style

- .changeset/clever-oranges-deny.md
- packages/machines/angle-slider/src/angle-slider.machine.ts
The end key sets value to 360.
Expected behaviour is 359
This PR fixes that
> fix: angle-slider max value

- .changeset/smart-games-watch.md
- e2e/models/popover.model.ts
- e2e/popover.e2e.ts
- packages/machines/combobox/src/combobox.machine.ts
- packages/machines/date-picker/src/date-picker.props.ts
- packages/machines/dialog/package.json
- packages/machines/dialog/src/dialog.machine.ts
- packages/machines/popover/package.json
- packages/machines/popover/src/popover.machine.ts
- packages/utilities/aria-hidden/package.json
- packages/utilities/aria-hidden/src/aria-hidden.ts
- packages/utilities/aria-hidden/src/index.ts
- packages/utilities/aria-hidden/src/walk-tree-outside.ts
- packages/utilities/focus-trap/src/index.ts
- pnpm-lock.yaml
📝 Description
The previous hideOthers method caused accessibility issues when aria-hidden was used on focused elements, triggering errors.
⛳️ Current behavior (updates)
Using hideOthers results in the error:
Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: button
🚀 New behavior
[supressOthers](https://github.com/theKashey/aria-hidden?tab=readme-ov-file#inert)
> While aria-hidden played important role in the past and will play in the …
> fix(aria-hidden): accessibility warning

- shared/src/controls.ts
tiny carouselControls prop key type fix
Yes but easy to be updated from consumer.
N/A
> fix: :pencil2: fix a typo for carouselControls

- .xstate/floating-panel.js
- .xstate/menu.js
- packages/anatomy/tests/create-anatomy.test.ts
- packages/core/README.md
- packages/core/src/machine.ts
- packages/core/tests/delayed-transitions.test.ts
- packages/docs/data/api.json
- packages/machines/accordion/src/accordion.types.ts
- packages/machines/combobox/src/combobox.types.ts
- packages/machines/floating-panel/src/floating-panel.machine.ts
- packages/machines/menu/src/menu.machine.ts
- packages/machines/number-input/src/number-input.dom.ts
- packages/machines/number-input/src/number-input.machine.ts
- packages/machines/pin-input/src/pin-input.machine.ts
- packages/machines/tags-input/src/tags-input.types.ts
- packages/utilities/dismissable/src/pointer-event-outside.ts
- packages/utilities/dom-event/src/request-pointer-lock.ts
- packages/utilities/i18n-utils/README.md
- packages/utilities/interact-outside/README.md
- packages/utilities/interact-outside/package.json
- packages/utilities/number/src/scale.ts
- packages/utilities/rect/src/from-window.ts
- packages/utilities/remove-scroll/src/index.ts
More typo fixes from `packages/` folder
Might be some breaking changes from the following files, but they tend to be minor changes.
`.xstate/floating-panel.js`, `.xstate/menu.js`, `packages/machines/menu/src/menu.machine.ts` , `packages/machines/floating-panel/src/floating-panel.machine.ts`, `packages/machines/number-input/src/number-input.dom.ts` 
N/A
> fix: :pencil2: fix typos from packages/ folders

- .changeset/cold-trainers-bathe.md
- packages/machines/file-upload/src/file-upload.machine.ts
Closes https://github.com/chakra-ui/zag/issues/2107
Adds support for the `accept` attribute in the File Upload machine, ensuring that the hidden input respects the file type restrictions.
Previously, the file upload component did not pass the `accept` attribute to the hidden input, which meant that the file picker would accept all file types regardless of any specified restrictions.
- Added `accept: ctx.accept` to the machine's context
- The hidden input now receives the `accept` attribute, limiting file selection to specified file types
- Maintains existing functionality while improving file type filtering
The change is a non-breaking improvement to the existing File Upload component.
- Bug discovered on documentation page for File Upload
- Reproduces at: …
> fix: ensure accept attribute is applied to file upload input

- .changeset/mean-apes-build.md
- packages/machines/accordion/src/accordion.connect.ts
Closes #2246 
Fix the bug #2246
Only the first value of the array was set when call `setValue` of `Accordion` 
all the values passed provided to setValue is set correctly.
No.
It looks like V1 has the same issue, hopefully this pull request will help.
> fix(accordion): check multiple values

- .changeset/great-glasses-change.md
- packages/utilities/aria-hidden/src/aria-hidden.ts
- packages/utilities/aria-hidden/src/walk-tree-outside.ts
Closes #2248
Set `aria-hidden="true"` instead of `aria-hidden=""` to hide elements for accessibility reasons.
Current implementation does not work.
Set `aria-hidden="true"` instead of `aria-hidden=""`.
No
> fix: explicitly set aria-hidden attribute to true

- e2e/pin-input.e2e.ts
Closes # 
To cover the fix in 「Fix issue where editing existing values don't work as expected.」https://github.com/chakra-ui/zag/commit/2ff622d1470f45cac0b359265212811402a0af3e
> test: add new e2e testing case for pin input

- .changeset/odd-students-hug.md
- packages/machines/checkbox/src/checkbox.connect.ts
When upgrading to ark v5, I noticated that my checkboxes received its invalid styling even when it was valid. This is because zag now passes `data-invalid="false"` to the dom. It used to just omit the attribute if it was false. The current behavior is fine, but the previous one is better when using Panda.
No, as I'm assuming this was unintentional.
> fix: checkbox should not set `data-invalid` when invalid is false

- .changeset/sixty-sides-fail.md
- packages/machines/slider/src/slider.style.ts
- packages/machines/slider/src/slider.types.ts
- shared/src/controls.ts
- website/data/components/slider.mdx
Closes #2236
The slider has an origin property that sets the start position of the filled track for single values. It currently includes "start" and "center" but misses an "end" option. 
An "end" option is useful in scenarios where the slider value functions as a threshold to include values above it. Then it might make more sense to have the track filled from the thumb to the end rather than from the start to the thumb.
Now the origin property has option "start" (default) and "center". For the "start" value, the track is filled from start (left in LTR contexts, right in RTL contexts) to the thumb. For "center", the track is filled from the center (50%) to the thumb.
This PR adds the origin option "end" to the slider. 
This PR also explains effect of this property more clearly.
No
> feat(slider): add option "end" to the slider's origin property

- .changeset/twenty-singers-notice.md
- packages/machines/file-upload/src/file-upload.types.ts
- packages/machines/progress/src/progress.types.ts
This PR updates the `FileUploadApi` and `ProgressApi` interfaces by adding a default type parameter (`= PropTypes`).
This change allows consumers to omit the type argument when the default is sufficient.
Previously, both API types required explicitly providing a `PropTypes` every time they were used.
The generic interfaces now default to `PropTypes` if no type argument is provided, reducing boilerplate and improving developer experience.
No
> chore(file-upload, progress): add default type parameter to api interface

- .changeset/slimy-suns-brake.md
- packages/utilities/focus-visible/src/index.ts
Assigning to the HTMLElement's prototype directly may lead to an error in some setups.
For example, happy-dom's prototypes seem to be readonly (see https://github.com/capricorn86/happy-dom/issues/1214).
Testing a UI using Chakra's Checkbox component can lead to errors such as this:
```
TypeError: Cannot set property focus of [object Object] which has only a getter
❯ setupGlobalFocusEvents ../node_modules/.pnpm/@zag-js+focus-visible@1.12.0/node_modules/@zag-js/focus-visible/dist/index.mjs:71:35
❯ trackFocusVisible ../node_modules/.pnpm/@zag-js+focus-visible@1.12.0/node_modules/@zag-js/focus-visible/dist/index.mjs:145:3
❯ trackFocusVisible ../node_modules/.pnpm/@zag-js+radio-group@1.12.0/node_modules/@zag-js/radio-group/dist/index.mjs:343:16
❯ effect …
```
> fix: use Object.defineProperty instead of assignment

- .changeset/moody-lamps-cheat.md
- packages/utilities/remove-scroll/src/index.ts
Closes: no issue to close, but related to [#2451](https://github.com/chakra-ui/zag/issues/2451#issuecomment-2876831171)
This PR updates the scroll-lock utility to calculate scrollbarWidth before setting the data-scroll-lock attribute.
This makes it compatible with CSS workarounds like:
```css
html:has([data-scroll-lock]) {
overflow: hidden;
}
```
...which are used in setups where the html element is a container. 
- `scrollbarWidth` is calculated after adding the scroll-lock attribute to the `<body>`.
- In setups using `html:has([data-scroll-lock])`, this changes the layout before scrollbarWidth is calculated, leading to incorrect values and layout shifts. 
- The `scroll-lock` attribute is applied after `scrollbarWidth` is calculated.
- This ensures that the width is measured before the …
> Fix scrollbar width calculation before DOM change for scroll-lock workaround compatibility

- .changeset/stale-clouds-listen.md
- packages/machines/carousel/src/carousel.machine.ts
This pull request resolves the high-priority bug reported in #2508,
where the carousel machine enters an infinite loop if the slidesPerPage prop is set to 0.
**The Problem**
As identified in the issue, when slidesPerPage is 0 and slidesPerMove is "auto", the perMove variable within the getPageSnapPoints utility is calculated as 0. This causes the for loop responsible for generating snap points to become an infinite loop (i += 0), leading to the browser tab hanging and crashing.
The Solution
This PR implements a simple guard clause at the beginning of the getPageSnapPoints function.
It now checks if slidesPerPage is 0 before any calculations occur.
If the condition is met, the function immediately returns an empty array, gracefully handling the invalid configuration and preventing the …
> fix(carousel): Prevent infinite loop when slidesPerPage is 0

- .changeset/wide-suits-wonder.md
- packages/machines/file-upload/src/file-upload.machine.ts
Closes #2513 
Fix undefined value being set in acceptedFiles array when no files are accepted in single-file upload mode.
When `maxFiles` is 1 and all files are rejected during validation, the `setFiles` action sets `acceptedFiles` to `[undefined]` because it accesses `acceptedFiles[0]` on an empty array.
When no files are accepted in single-file mode, `acceptedFiles` is now set to an empty array `[]` instead of `[undefined]`, ensuring type safety and preventing potential runtime errors.
No
> fix(file-upload): prevent undefined in acceptedFiles when no files accepted

- website/components/multi-framework.tsx
A different version FrameworkButton is created every render because the component definition is nested within another component definition.
Extract the FrameworkButton component definition outside so it isn't a nested component definition.
A different version of FrameworkButton is created every render, requiring you to double click the buttons to trigger the tab change.
A single click will now cause the tab change.
No
https://react.dev/learn/preserving-and-resetting-state#different-components-at-the-same-position-reset-state:~:text=This%20is%20why%20you%20should%20not%20nest%20component%20function%20definitions.
> docs: pull out FrameworkButton component definition

- .changeset/gentle-tomatoes-remain.md
- examples/next-ts/pages/date-picker-month-range.tsx
- packages/machines/date-picker/src/date-picker.connect.ts
- packages/machines/date-picker/src/date-picker.machine.ts
- packages/machines/date-picker/src/date-picker.types.ts
- shared/src/routes.ts
Closes #2556
When using selectionMode="range" with view="month", two issues were present:
1. An error was thrown when resetting the selection (e.g., third selection):
```
Uncaught TypeError: date.toDate is not a function
// or
Cannot read properties of undefined (reading 'toString')
```
2. The `in-range` styling didn’t work correctly—between selected months, the intermediate months lacked the data-in-range attribute.
Both issues stemmed from incorrect handling of month values (number instead of Date) and missing logic for marking range states.
This PR corrects both:
- Ensures resetSelection wraps month values as Date.
- Fixes cellState.inRange logic
And added a working example demonstrating both resetSelection behavior and in-range styling for month + range.
- Runtime error occurs on …
> fix: error in range mode with month view due to incorrect value in resetSelection

- .changeset/dull-schools-kneel.md
- examples/next-ts/pages/date-picker-inline.tsx
- packages/machines/date-picker/src/date-picker.connect.ts
- shared/src/css/date-picker.css
- expose `data-inline` attribute on Content part to enable distinct styling for inline date pickers versus popover date pickers
- implement `/date-picker-inline` route in the next-ts example
> feat(date-picker): inline data attribute

- packages/machines/menu/src/menu.connect.ts
Closes # 
add data-state for context menu trigger
contextmenu trigger element miss the `data-state` attribute
contextmenu trigger element will get a `data-state` attribute
No
> feat: add data-state for context menu trigger

- .changeset/tricky-meals-appear.md
- packages/machines/scroll-area/src/scroll-area.connect.ts
- packages/machines/scroll-area/src/scroll-area.machine.ts
- packages/machines/scroll-area/src/scroll-area.types.ts
First of all, thank you for releasing the new ScrollArea component — I’ve been happily using it in my project. 🎉
While integrating it, I noticed one small improvement that could make the developer experience even better.
This PR adds a data-dragging attribute to the scrollbar thumb, enabling developers to style the thumb differently when it is actively being dragged.
This allows us to replicate the familiar macOS scroll experience, where the thumb visually changes during drag for improved usability.
Currently, the ScrollArea thumb only exposes a data-hover state.
There is no way to detect or differentiate when the thumb is being actively dragged, which limits the ability to reproduce native-like scroll behaviors.
- Introduces a `data-dragging` attribute on the scrollbar and thumb.
- When …
> feat(scroll-area): add dragging state to scroll area context and machine

- .changeset/floppy-waves-speak.md
- packages/machines/bottom-sheet/src/bottom-sheet.machine.ts
Closes # 
Fix the issue where controlled props are not working in the bottom sheet.
The open state of the bottom sheet can't be controlled using the `open` prop.
The open state of the bottom sheet can be controlled using the `open` prop.
> fix(bottom-sheet): controlled props

- .changeset/little-eyes-dress.md
- packages/utilities/i18n-utils/src/format-bytes.ts
- packages/utilities/i18n-utils/tests/format-byte.test.ts
In computing, there are two competing definitions of what “kilo,” “mega,” “giga,” etc., mean when applied to bytes:
**Decimal** (SI definition)
1 kilobyte (KB) = 1000 bytes
1 megabyte (MB) = 1000² bytes
Common in disk storage, networking, and marketing.
**Binary** (IEC definition)
1 kibibyte (KiB) = 1024 bytes
1 mebibyte (MiB) = 1024² bytes
Used in memory, OS-level reporting, and low-level computing
I added `definition` so developers can choose between default `decimal` (1000) and `binary` (1024) unit systems, ensuring accurate and context-appropriate byte formatting.
> formatByte: Add unit system property

- .changeset/rude-kings-listen.md
- packages/machines/slider/src/slider.props.ts
Closes #2725
Adds the `splitMarkerProps` utility
Incremental feature, no behaviour will change
Users can split marker props now.
No
> feat(slider): add `splitMarkerProps` helper

- website/data/components/collapsible.mdx
Updates the collapsible animation code snippet to support the newly introduced collapsed height.
Falls back to 0.
example is not working
example is working
no
> docs: use css variable for collapsed height in animations
