chakra-ui/zag

.changeset/olive-humans-taste.md, packages/frameworks/solid/src/prop-types.ts
=> fix: solid prop-types

.changeset/healthy-avocados-tie.md, .vscode/launch.json, e2e/numberinput.e2e.ts, packages/utilities/number/__tests__/number.test.ts, packages/utilities/number/src/number.ts
Closes #73
Fixed issue related to how we round value to precision
=> fix: precision calculations

.changeset/flat-wolves-beg.md, e2e/__utils.ts, e2e/numberinput.e2e.ts, e2e/rating.e2e.ts, packages/machines/rating/src/rating.connect.ts, shared/controls.ts
Add tests for rating component
=> test: add ratings test

.changeset/nasty-camels-jump.md, .changeset/serious-timers-matter.md, .xstate/menu.js, .xstate/tags-input.js, packages/core/src/machine.ts, packages/core/src/transition-utils.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/core/tests/transition.test.ts, packages/machines/menu/src/menu.machine.ts, packages/machines/tags-input/src/tags-input.machine.ts, packages/utilities/dom/src/live-region.ts, shared/controls.ts
Fix issue where transition object gets mutated
=> fix: machine transition

.changeset/good-tips-beam.md, .xstate/tags-input.js, packages/machines/tags-input/src/tags-input.connect.ts, packages/machines/tags-input/src/tags-input.machine.ts
api to set the value of a specific tag, based on the index of the tag
```js
api.setValueAtIndex(2, 'newValue')
```
=> feat(tags-input): api to set the value of a specific tag

.xstate/dialog.js, .xstate/popover.js, scripts/src/commands/visualize.ts
Closes #125
Visualizer: https://state-machine-viz.vercel.app/pr/126/dialog
Conditional expressions in target breaks visualizer
Modified visualizer generator to account for conditional expressions
visualizer generator now accounts for conditional expressions
=> chore: allow conditional expression in target

.github/workflows/visualize.yml
Add github action for workflow to add visualizer links to pull requests.
=> chore: github workflow to add visualizer links

plop/machine-examples/next-ts/pages/{{machine}}.tsx.hbs, plop/machine-examples/solid-ts/src/pages/{{machine}}.tsx.hbs, plop/machine-examples/vue-ts/src/pages/{{machine}}.tsx.hbs, plopfile.js, shared/src/routes.ts
Automate examples route generation. Adds creation of components for all frameworks, and addition to shared routes, when a new machine ie generated with plop
=> chore: automate examples generation

.changeset/blue-chairs-allow.md, examples/next-ts/pages/combobox.tsx, examples/solid-ts/src/app.tsx, examples/solid-ts/src/components/state-visualizer.tsx, examples/solid-ts/src/components/toolbar.tsx, examples/solid-ts/src/pages/accordion.tsx, examples/solid-ts/src/pages/checkbox.tsx, examples/solid-ts/src/pages/combobox.tsx, examples/solid-ts/src/pages/context-menu.tsx, examples/solid-ts/src/pages/dialog-default-open.tsx, examples/solid-ts/src/pages/dialog.tsx, examples/solid-ts/src/pages/editable.tsx, examples/solid-ts/src/pages/home.tsx, examples/solid-ts/src/pages/menu-options.tsx, examples/solid-ts/src/pages/menu.tsx, examples/solid-ts/src/pages/nested-menu.tsx, examples/solid-ts/src/pages/number-input.tsx, examples/solid-ts/src/pages/pin-input.tsx, examples/solid-ts/src/pages/popover.tsx, examples/solid-ts/src/pages/range-slider.tsx, examples/solid-ts/src/pages/rating.tsx, examples/solid-ts/src/pages/slider.tsx, examples/solid-ts/src/pages/splitter.tsx, examples/solid-ts/src/pages/tabs.tsx, examples/solid-ts/src/pages/tags-input.tsx, examples/solid-ts/src/pages/toast.tsx, examples/solid-ts/src/pages/toggle.tsx, examples/solid-ts/src/pages/tooltip.tsx, packages/frameworks/solid/src/use-machine.ts, shared/src/controls.ts
improve ssr solid by omiting useSetup
=> refactor: improve ssr solid

.changeset/olive-laws-lick.md, examples/vue-ts/src/pages/accordion.tsx, examples/vue-ts/src/pages/checkbox.tsx, examples/vue-ts/src/pages/combobox.tsx, examples/vue-ts/src/pages/context-menu.tsx, examples/vue-ts/src/pages/dialog-default-open.tsx, examples/vue-ts/src/pages/dialog.tsx, examples/vue-ts/src/pages/editable.tsx, examples/vue-ts/src/pages/menu-options.tsx, examples/vue-ts/src/pages/menu.tsx, examples/vue-ts/src/pages/nested-menu.tsx, examples/vue-ts/src/pages/number-input.tsx, examples/vue-ts/src/pages/pin-input.tsx, examples/vue-ts/src/pages/popover.tsx, examples/vue-ts/src/pages/range-slider.tsx, examples/vue-ts/src/pages/rating.tsx, examples/vue-ts/src/pages/slider.tsx, examples/vue-ts/src/pages/splitter.tsx, examples/vue-ts/src/pages/tabs.tsx, examples/vue-ts/src/pages/tags-input.tsx, examples/vue-ts/src/pages/toast.tsx, examples/vue-ts/src/pages/toggle.tsx, examples/vue-ts/src/pages/tooltip.tsx, packages/frameworks/vue/src/use-machine.ts
Improve vue ssr by omitting `useSetup` step
=> refactor: improve ssr vue

.changeset/gold-berries-jump.md, packages/machines/rating/src/rating.types.ts, packages/machines/tags-input/src/tags-input.types.ts
move initial value to private context
=> chore: move initial value to private context

README.md
=> chore: fix typos in README.md

.changeset/heavy-meals-kiss.md, packages/machines/rating/src/rating.connect.ts, packages/machines/rating/src/rating.machine.ts
=> fix (rating): midway select

.changeset/cold-poets-pay.md, .changeset/tricky-chefs-watch.md, .xstate/radio.js, .xstate/rating.js, .xstate/tags-input.js, examples/next-ts/pages/rating.tsx, packages/machines/rating/src/rating.dom.ts, packages/machines/rating/src/rating.machine.ts, packages/machines/tags-input/src/tags-input.machine.ts
=> fix: add form reset listener and fieldset disabled tracker to rating and tags input

.changeset/popular-clocks-brush.md, .xstate/number-input.js, packages/machines/number-input/src/number-input.machine.ts
=> fix(number-input): clamp when value is programmatically set

examples/vue-ts/src/pages/menu.tsx, pnpm-lock.yaml, shared/package.json
=> chore: remote emotion css

.changeset/nasty-ghosts-press.md, packages/machines/radio/src/radio.connect.ts
Clicking label should focus right radio item.
=> Fix radio label focus

.changeset/big-poets-approve.md, examples/next-ts/pages/pin-input.tsx, packages/machines/pin-input/src/pin-input.connect.ts, packages/machines/pin-input/src/pin-input.dom.ts, packages/machines/pin-input/src/pin-input.types.ts
Add label to pin input
Closes #287
=> feat(pin-input): add label

.changeset/popular-zoos-stare.md, packages/machines/pressable/src/pressable.connect.ts, shared/src/style.css
fix(pressable): long press firing when pressable is disabled
=> fix(pressable): long press firing when pressable is disabled

plop/machine/package.json.hbs, plop/machine/src/{{machine}}.machine.ts.hbs, plop/machine/src/{{machine}}.types.ts.hbs
=> chore: update plop template

.changeset/little-suits-flow.md, .xstate/hover-card.js, examples/next-ts/package.json, examples/next-ts/pages/hover-card.tsx, examples/solid-ts/package.json, examples/solid-ts/src/pages/hover-card.tsx, examples/solid-ts/src/routes.ts, examples/vue-ts/package.json, examples/vue-ts/src/pages/hover-card.tsx, examples/vue-ts/src/routes.ts, packages/machines/hover-card/README.md, packages/machines/hover-card/index.ts, packages/machines/hover-card/package.json, packages/machines/hover-card/src/hover-card.connect.ts, packages/machines/hover-card/src/hover-card.dom.ts, packages/machines/hover-card/src/hover-card.machine.ts, packages/machines/hover-card/src/hover-card.types.ts, packages/machines/hover-card/src/index.ts, packages/machines/hover-card/tsconfig.json, pnpm-lock.yaml, shared/src/controls.ts, shared/src/routes.ts, shared/src/style.css
=> feat: hover card machine

.changeset/red-parrots-run.md, packages/machines/tags-input/src/tags-input.connect.ts
fix(tags-input): android issue
Fixes #293
=> fix(tags-input): android issue

.changeset/early-news-explode.md, packages/machines/hover-card/src/hover-card.dom.ts
=> fix anatomy ids

.changeset/pink-knives-fry.md, packages/machines/pin-input/src/pin-input.connect.ts
=> fix(pin-input):  issue

.changeset/unlucky-days-roll.md, packages/machines/number-input/src/number-input.utils.ts
fix(number-input): disallow E
Fixes #313
=> fix(number-input): disallow E

.changeset/hot-items-explain.md, .xstate/hover-card.js, packages/machines/hover-card/src/hover-card.machine.ts
fix(hover-card): focus+hover behaviour
=> fix(hover-card): focus+hover behaviour

.changeset/big-moons-allow.md, packages/machines/combobox/src/combobox.connect.ts, packages/machines/combobox/src/combobox.machine.ts, packages/machines/combobox/src/combobox.types.ts, packages/machines/editable/src/editable.connect.ts, packages/machines/editable/src/editable.machine.ts, packages/machines/editable/src/editable.types.ts, packages/machines/number-input/src/number-input.connect.ts, packages/machines/number-input/src/number-input.machine.ts, packages/machines/number-input/src/number-input.types.ts, packages/machines/pagination/src/pagination.connect.ts, packages/machines/pagination/src/pagination.machine.ts, packages/machines/pagination/src/pagination.types.ts, packages/machines/pin-input/src/pin-input.connect.ts, packages/machines/pin-input/src/pin-input.machine.ts, packages/machines/pin-input/src/pin-input.types.ts, packages/machines/rating/src/rating.connect.ts, packages/machines/rating/src/rating.machine.ts, packages/machines/rating/src/rating.types.ts, packages/machines/tabs/src/tabs.connect.ts, packages/machines/tabs/src/tabs.machine.ts, packages/machines/tabs/src/tabs.types.ts, packages/machines/tags-input/src/tags-input.connect.ts, packages/machines/tags-input/src/tags-input.machine.ts, packages/machines/tags-input/src/tags-input.types.ts
rename messages to translations
=> chore: rename messages to translations

e2e/pagination.e2e.ts
=> chore(pagination): fix tests

.changeset/giant-steaks-return.md, .xstate/pin-input.js, examples/next-ts/components/toolbar.tsx, packages/machines/pin-input/src/pin-input.connect.ts, packages/machines/pin-input/src/pin-input.machine.ts, packages/machines/pin-input/src/pin-input.types.ts
=> fix(pin-input): make component uncontrolled

.changeset/eighty-frogs-promise.md, .xstate/combobox.js, packages/machines/combobox/src/combobox.connect.ts, packages/machines/combobox/src/combobox.machine.ts
Make combobox component uncontrolled
=> fix(combobox-input): make component uncontrolled

.changeset/empty-weeks-sort.md, .xstate/accordion.js, .xstate/checkbox.js, .xstate/combobox.js, .xstate/dialog.js, .xstate/editable.js, .xstate/hover-card.js, .xstate/menu.js, .xstate/number-input.js, .xstate/pagination.js, .xstate/pin-input.js, .xstate/popover.js, .xstate/pressable.js, .xstate/radio.js, .xstate/range-slider.js, .xstate/rating.js, .xstate/slider.js, .xstate/splitter.js, .xstate/tabs.js, .xstate/tags-input.js, .xstate/toast.js, .xstate/toggle.js, .xstate/tooltip.js, packages/machines/combobox/src/combobox.machine.ts, packages/machines/combobox/src/combobox.types.ts
Closes #353
Add positioning to context
=> fix(combobox): add posiitoning to context

.changeset/cool-coats-shake.md, packages/utilities/dom/src/query.ts, pnpm-lock.yaml
add `dispatchEvent` helper to dom-utils
=> feat(dom-utils): add `dispatchEvent` helper

.github/workflows/playwright.yml, playwright.config.ts
This PR speeds up Playwright tests by using caching and sharding strategies
=> Speed up Playwright tests

.changeset/cool-coats-shake.md, .changeset/many-cycles-move.md, examples/next-ts/package.json, examples/solid-ts/package.json, examples/vue-ts/package.json, packages/utilities/dom-query/README.md, packages/utilities/dom-query/index.ts, packages/utilities/dom-query/package.json, packages/utilities/dom-query/src/contains.ts, packages/utilities/dom-query/src/get-element.ts, packages/utilities/dom-query/src/helpers.ts, packages/utilities/dom-query/src/index.ts, packages/utilities/dom-query/src/is-element.ts, packages/utilities/dom-query/tsconfig.json, packages/utilities/dom/src/query.ts, pnpm-lock.yaml
- Move `defineDomHelpers` to new package `@zag-js/dom-query`
- Add `createEmitter` and `createListener` helpers for custom event handling
=> feat(dom): add emitter and listener

.xstate/checkbox.js, packages/machines/checkbox/src/checkbox.connect.ts, packages/machines/checkbox/src/checkbox.machine.ts, packages/machines/checkbox/src/checkbox.types.ts
Fix SSR issue with Checkbox.
The reason this is happening is that we're checking defaultChecked after the machine starts, not in the initial state of the machine.
=> fix(checkbox): ssr issue

.changeset/twelve-schools-build.md, .xstate/checkbox.js, .xstate/radio.js, .xstate/range-slider.js, .xstate/rating.js, .xstate/slider.js, .xstate/tags-input.js, examples/next-ts/pages/checkbox.tsx, packages/machines/checkbox/src/checkbox.machine.ts, packages/machines/radio/src/radio.machine.ts, packages/machines/range-slider/src/range-slider.machine.ts, packages/machines/rating/src/rating.machine.ts, packages/machines/slider/src/slider.machine.ts, packages/machines/tags-input/src/tags-input.machine.ts, packages/utilities/form-utils/src/form.ts
Simplify the form element machines to use `trackFormControl`
=> refactor: machine to use new form utils approach

.xstate/select.js, e2e/select.e2e.ts, packages/machines/select/src/select.machine.ts, packages/machines/select/src/select.types.ts, shared/src/controls.ts
add `closeOnSelect` option to select machine
=> feat: add `closeOnSelect` option to select

.github/workflows/playwright.yml
remove playwright report action
=> chore: remove playwright report action

examples/next-ts/pages/select.tsx, examples/solid-ts/src/pages/select.tsx, examples/vue-ts/src/pages/select.tsx
=> chore: render select in portal

.changeset/clean-points-mate.md, .xstate/menu.js, packages/machines/menu/src/menu.connect.ts, packages/machines/menu/src/menu.dom.ts, packages/machines/menu/src/menu.machine.ts, packages/machines/menu/src/menu.types.ts
change `activeId` to `highlightedId`
=> refactor: change `activeId` to `highlightedId`

.changeset/twenty-carrots-allow.md, e2e/combobox.e2e.ts, examples/next-ts/pages/combobox.tsx, examples/solid-ts/src/pages/combobox.tsx, examples/vue-ts/src/pages/combobox.tsx, packages/machines/combobox/src/combobox.anatomy.ts, packages/machines/combobox/src/combobox.connect.ts, packages/machines/combobox/src/combobox.dom.ts, packages/machines/combobox/src/combobox.machine.ts, packages/machines/combobox/src/combobox.types.ts, shared/src/style.css
=> refactor: combobox

.changeset/seven-fireants-tell.md, packages/machines/menu/src/menu.machine.ts, packages/machines/menu/src/menu.types.ts
=> chore: menu onselect refactor

.changeset/many-pugs-watch.md, packages/machines/range-slider/src/range-slider.style.ts
Fix negative range sliders/ offset logic
=> fix(range-slider): negative offsets

.changeset/seven-pants-hunt.md, .xstate/pin-input.js, packages/machines/pin-input/src/pin-input.machine.ts
fix(pin-input): controlled mode issues
=> fix(pin-input): controlled mode issues

examples/vue-ts/tsconfig.json
Closes # 
Adds `jsx: preserve` to Vue playground's tsconfig.json
N/A
N/A
No
N/A
=> fix: add jsx preserve to tssconfig

.changeset/stale-sheep-march.md, .xstate/pressable.js, packages/machines/pressable/src/pressable.connect.ts, packages/machines/pressable/src/pressable.machine.ts
=> Fix pressable triggering `onPress` after long press

examples/svelte-kit/src/routes/accordion/+page.svelte, examples/svelte-kit/src/routes/menu/+page.svelte, examples/svelte-kit/src/routes/select/+page.svelte, examples/svelte-kit/src/stores/controls/index.ts, examples/svelte-kit/src/stores/controls/ui.svelte, packages/frameworks/svelte/src/use-machine.ts, plop/machine-examples/svelte-kit/src/routes/{{machine}}/+page.svelte.hbs
This is in retrospect to what we talked about in the comment of #630 
It handles the transient context as a writable
=> feat(svelte): add writable context

website/data/snippets/react/segmented-control/usage.mdx, website/data/snippets/solid/segmented-control/usage.mdx, website/data/snippets/vue-jsx/segmented-control/usage.mdx, website/data/snippets/vue-sfc/segmented-control/usage.mdx
Closes # 
`id` doesn't exist on items. `value` should be used instead.
=> docs: replace id with value in segmented control snippets

.changeset/hip-waves-deny.md, .changeset/lucky-boxes-rhyme.md, packages/docs/api.json, packages/machines/combobox/src/combobox.connect.ts, packages/machines/combobox/src/combobox.dom.ts, packages/machines/combobox/src/combobox.machine.ts, packages/machines/combobox/src/combobox.types.ts, packages/machines/menu/src/menu.connect.ts, packages/machines/menu/src/menu.machine.ts, packages/machines/select/src/select.connect.ts, shared/src/controls.ts
Closes #758
Closes #756
Closes #659
Closes #605
Closes #530
This PR improves the option click and pointer experience on mobile.
=> fix: option clicking and pointer

e2e/menu.e2e.ts, examples/next-ts/pages/menu.tsx, examples/solid-ts/src/pages/menu.tsx, examples/vue-ts/src/pages/menu.tsx
Fix tests for Menu machine.
Tests for Menu pass for React.
Tests for Menu pass for React, Solid and Vue.
No, no need for a changeset either
=> fix: fix Menu tests for Vue and Solid

.changeset/sharp-dots-count.md, .xstate/combobox.js, examples/next-ts/pages/select-async.tsx, examples/next-ts/pages/select-in-dialog.tsx, examples/next-ts/pages/select.tsx, examples/nuxt-ts/pages/select.vue, examples/solid-ts/src/pages/select.tsx, examples/vue-ts/src/pages/select.tsx, packages/machines/combobox/package.json, packages/machines/combobox/src/combobox.anatomy.ts, packages/machines/combobox/src/combobox.connect.ts, packages/machines/combobox/src/combobox.machine.ts, packages/machines/combobox/src/combobox.types.ts, packages/machines/combobox/src/index.ts, packages/machines/select/src/select.anatomy.ts, packages/machines/select/src/select.connect.ts, packages/machines/select/src/select.dom.ts, packages/machines/select/src/select.types.ts, pnpm-lock.yaml, shared/src/style.css, website/components/machines/select.tsx, website/data/snippets/react/select/usage-with-form.mdx, website/data/snippets/react/select/usage.mdx, website/data/snippets/solid/select/usage-with-form.mdx, website/data/snippets/vue-jsx/select/usage-with-form.mdx, website/data/snippets/vue-sfc/select/usage-with-form.mdx
Ensure the combobox and select parts are consistent and aligned.
=> feat: align combobox and select parts

e2e/color-picker.e2e.ts, examples/next-ts/pages/color-picker.tsx, examples/solid-ts/src/pages/color-picker.tsx, examples/vue-ts/src/pages/color-picker.tsx
add swatch tests
To-do in next PRs:
- test HSV channel inputs
- test channel-slider-track (hue, alpha)
- test area
No
=> test(color-picker): add swatch tests

examples/solid-ts/src/pages/segment-control.tsx, website/data/components/segmented-control.mdx, website/data/snippets/solid/segmented-control/usage.mdx
Updating Solid docs/examples
No
I'm planning to fix a minor bug/inconvenience in radio, but first I wanted to clean this up
=> docs(segmented-control): update solid docs/examples

CHANGELOG.md
=> fix(changelog): radio anatomy changes missing function

examples/next-ts/pages/tooltip.tsx, examples/solid-ts/src/pages/tooltip.tsx, examples/vue-ts/src/pages/tooltip.tsx
CI failed from PR #1041 
Failed all CI with tooltip
I've fixed CI and updated the examples with Tooltip
No
=> fix: Fix CI and updated example for tooltip

packages/machines/progress/src/index.ts, packages/machines/progress/src/progress.types.ts
Missing types make `progress` difficult to implement
Less types
More types
No
> Kage Bunshin no Jutsu
=> fix(progress): expose more types

website/data/snippets/vue-jsx/select/usage-with-form.mdx, website/data/snippets/vue-jsx/select/usage.mdx
Closes # 
fix: select vue-jsx snippets
Update doc snippet errors
No
=> fix: select vue-jsx snippets

packages/machines/select/src/select.connect.ts
Closes # 
fixed select clearTrigger disabled state
clearTrigger disabled state cannot inherit from the Root
=> fix: select clearTrigger disabled

.changeset/red-glasses-yell.md, packages/machines/combobox/src/combobox.connect.ts
Closes # 
fix combobox item disabled
`ComboboxItem` disabled state cannot inherit the Root
=> fix: combobox item disabled

website/components/mdx-components.tsx, website/components/prop-table.tsx, website/plop/component.mdx.hbs, website/plop/snippet/react/usage.mdx.hbs, website/plop/snippet/solid/usage.mdx.hbs, website/plop/snippet/vue-jsx/usage.mdx.hbs, website/plop/snippet/vue-sfc/usage.mdx.hbs
Plops improved. In addition, I fixed some cases when Astro crashes if we provide a bad name by mistake,
Stub plops, almost empty
More helpful plops
=> docs: improve plop

website/data/snippets/react/toast/usage.mdx, website/data/snippets/solid/toast/usage.mdx, website/data/snippets/vue-jsx/toast/usage.mdx, website/data/snippets/vue-sfc/toast/usage.mdx
Correct `placement` to prevent a type error in the example section of the Toast component.
```javascript
toast.create({
title: "Data submitted!",
type: "success",
placement: "bottom-right",  // or "top-right"
})
```
```javascript
toast.create({
title: "Data submitted!",
type: "success",
placement: "bottom-end",  // or "top-end"
})
```
No
N/A
=> docs: fix toast placement

website/data/components/select.mdx
Closes #1165
- Update styling guide for select for select state data attrs
- Fix a misspelled word
Incorrect styling guide in docs.
Correct styling guide in docs.
No
Thanks `zag-js` team!
=> docs(select): update styling guide; typo

examples/next-app/app/dialog-controlled/page.tsx, examples/next-app/app/dialog-search-params/page.tsx, examples/next-app/components/dialog.tsx
Adding an example of dialog controlled by search params on next app example
There is no example with controlled dialog by search params
Now there is
No
I think this seems to be fixed in the new version: https://github.com/chakra-ui/zag/issues, right?
=> chore(examples): add dialog controlled by search params

packages/machines/tree-view/src/index.ts
=> fix(tree-view): expore missing types

.changeset/two-pugs-protect.md, packages/machines/collapsible/src/collapsible.types.ts, packages/machines/collapsible/src/index.ts
=> fix(collapsible): expose missing types

website/data/components/clipboard.mdx
=> docs: fix clipboard code block

packages/machines/file-upload/src/file-upload.machine.ts
=> fix: make sure onFileReject is called when no files are accepted

.changeset/spicy-pans-hug.md
=> chore: add missing changeset for file-upload fix

plop/machine-examples/next-ts/pages/{{machine}}.tsx.hbs, plop/machine-examples/nuxt-ts/pages/{{machine}}.vue.hbs, plop/machine-examples/solid-ts/src/pages/{{machine}}.tsx.hbs, plop/machine-examples/vue-ts/src/pages/{{machine}}.tsx.hbs, plopfile.js
Update helpers in handlebar expressions for machine file generation.
- Ensures named imports are camelCase if multi-word machine name
- Ensures shared route labels generate multi-word capitalized with no `-`
=> refactor(plop): update helper usage

website/components/machines/tabs.tsx, website/styles/machines/tabs.css
chore: fix tabs style
**Before**
**After**
=> chore: fix tabs style

website/data/snippets/solid/file-upload/usage.mdx
Closes # 
just correct file-upload example on website
None
None
None
=> doc: correct file-upload example on website

.changeset/giant-socks-explode.md, .xstate/presence.js, packages/docs/data/api.json, packages/machines/presence/src/presence.connect.ts, packages/machines/presence/src/presence.machine.ts, packages/machines/presence/src/presence.types.ts, pnpm-lock.yaml, starters/react/app/page.tsx, starters/react/app/presence/page.css, starters/react/app/presence/page.tsx, starters/react/components/presence.tsx, website/components/machines/presence.tsx, website/components/showcase.tsx, website/data/components/presence.mdx, website/data/snippets/react/presence/installation.mdx, website/data/snippets/react/presence/usage.mdx, website/data/snippets/solid/presence/installation.mdx, website/data/snippets/solid/presence/usage.mdx, website/data/snippets/vue-jsx/presence/installation.mdx, website/data/snippets/vue-jsx/presence/usage.mdx, website/data/snippets/vue-sfc/presence/installation.mdx, website/data/snippets/vue-sfc/presence/usage.mdx, website/package.json, website/sidebar.config.ts, website/styles/machines/index.css, website/styles/machines/presence.css
Add docs for the presence component. While writing the docs, I spotted some subtle bugs with the presence machine and refactored it.
=> docs: presence component

examples/next-ts/pages/date-picker-range.tsx, examples/svelte-ts/src/App.svelte, examples/svelte-ts/src/routes/date-picker-multi.svelte, examples/svelte-ts/src/routes/date-picker-range.svelte
Svelte add multi and range datepickers
=> chore(svelte): add multi and range datepickers

.changeset/lazy-vans-remember.md, examples/svelte-ts/src/App.svelte, examples/svelte-ts/src/routes/nested-menu.svelte, packages/core/src/merge-props.ts
=> fix(svelte): events props merging

packages/machines/time-picker/src/index.ts
Add the missing export of the `MachineApi` type for the time-picker component
No
=> feat(time-picker): export machine api type

examples/svelte-ts/package.json, packages/frameworks/svelte/package.json, pnpm-lock.yaml
Update VPS (vite-plugin-svelte) to the next tag to support svelte inspector.
=> chore: update vite-plugin-svelte to support svelte inspector

website/data/snippets/solid/date-picker/usage.mdx
chore: update solid date picker docs
=> chore: update solid date picker docs

website/data/snippets/vue-jsx/date-picker/usage.mdx, website/data/snippets/vue-sfc/date-picker/usage.mdx, website/data/snippets/vue-sfc/switch/usage.mdx
> Update code snippet for vue datepicker and update getHiddenInputProps for vue(sfc) switch
- `<input v-bind="api.getInputProps()" />` in switch (SFC)
- `Snippet not found` :( in Vue (JSX and SFC)
- `<input v-bind="api.getHiddenInputProps()" />` in switch (SFC)
- Added code snippet for Vue (JSX and SFC)
No
=> docs: datepicker and switch

examples/next-ts/pages/date-picker-multi.tsx, examples/next-ts/pages/date-picker.tsx, examples/svelte-ts/src/routes/date-picker-multi.svelte, examples/svelte-ts/src/routes/date-picker.svelte, examples/vue-ts/src/pages/date-picker.tsx, website/components/machines/date-picker.tsx, website/data/snippets/react/date-picker/usage.mdx, website/data/snippets/svelte/date-picker/usage.mdx, website/data/snippets/vue-jsx/date-picker/usage.mdx, website/data/snippets/vue-sfc/date-picker/usage.mdx
=> chore: date picker semantics

website/components/mutli-framework.tsx, website/lib/framework-utils.ts, website/pages/index.tsx
=> docs: hide svelte

.changeset/friendly-walls-think.md, packages/core/src/machine.ts, packages/core/src/types.ts, packages/frameworks/react/src/use-service.ts, packages/utilities/core/src/object.ts
Improves the HMR experience for components that rely heavily on state rather than context (dialog, combobox, select).
During HMR, the machine restarts back to the initial state
During HMR, the machine restarts back to the state before HMR, preserving the state, event, and context
No
=> react: improve hmr

plopfile.js
Remove redundant steps in plopfile
=> chore(repo): remove redundant steps in plopfile

plop/machine/src/{{machine}}.connect.ts.hbs
=> chore(repo): fix plopfile connect code

.changeset/kind-drinks-battle.md, packages/frameworks/svelte/package.json
Closes #1772 
Changes the `svelte` peer dependency.
Current version was: `>=5.0.0`
New version was: `^5.0.0-next.1`
No
-
=> fix(svelte): peer dep

packages/machines/editable/src/index.ts
=> fix(editable): export missing type

.github/workflows/pkg-pr.yml
chore: add pkg-pr-new workflow
=> chore: add pkg-pr-new workflow

.changeset/stale-emus-perform.md, packages/utilities/date-utils/src/normalize-year.ts, packages/utilities/date-utils/src/parse-date.ts, packages/utilities/date-utils/tests/normalize-year.test.ts, packages/utilities/date-utils/tests/parse-date.test.ts
Closes #1849
Parse date year corectly
=> fix: date parsing logic with locale

examples/qwik-ts/src/hooks/normalize-props.ts, examples/qwik-ts/src/routes/index.tsx
=> feat(qwik): add normalize props for qwik

website/data/snippets/svelte/combobox/usage.mdx, website/data/snippets/svelte/qr-code/installation.mdx, website/data/snippets/svelte/qr-code/usage.mdx, website/data/snippets/svelte/tour/installation.mdx, website/data/snippets/svelte/tour/usage.mdx
=> chore: fix svelte snippets

website/data/components/tour.mdx
Closes # 
Fix [Tour Docs](https://zagjs.com/components/react/tour) title.
[Tour Docs](https://zagjs.com/components/react/tour) title is Tooltip.
[Tour Docs](https://zagjs.com/components/react/tour) title is Tour.
No.
=> fix: tour title

examples/lit-ts/src/accordion-element.ts, examples/lit-ts/src/avatar-element.ts, examples/lit-ts/src/carousel-element.ts, examples/lit-ts/src/component.ts, examples/lit-ts/src/menu-element.ts
This is a small change to introduce a shared Component class to simplify the creation of Lit components with Zag machines
All Lit components in the example have duplicated code between them...
All Lit components in the example extends from a shared class...
No
I think this can be improved to be more type safety
=> feat: improve lit-ts example with shared Component class

website/data/overview/introduction.mdx
Closes # 
Hi everyone, I noticed that after fast-element v2, the https://explore.fast.design/components link seems broken, so I’ve changed it to https://fast.design/. Feel free to close this if it is not suitable.
No
=> docs: update the fast-components link

examples/next-ts/pages/angle-slider.tsx, packages/docs/data/accessibility.json, packages/docs/data/api.json, packages/docs/data/data-attr.json, pnpm-lock.yaml, website/components/machines/angle-slider.tsx, website/components/showcase.tsx, website/data/components/angle-slider.mdx, website/data/components/slider.mdx, website/data/snippets/react/angle-slider/installation.mdx, website/data/snippets/react/angle-slider/tick-marks.mdx, website/data/snippets/react/angle-slider/usage.mdx, website/data/snippets/solid/angle-slider/installation.mdx, website/data/snippets/solid/angle-slider/tick-marks.mdx, website/data/snippets/solid/angle-slider/usage.mdx, website/data/snippets/svelte/angle-slider/installation.mdx, website/data/snippets/svelte/angle-slider/tick-marks.mdx, website/data/snippets/svelte/angle-slider/usage.mdx, website/data/snippets/vue/angle-slider/installation.mdx, website/data/snippets/vue/angle-slider/tick-marks.mdx, website/data/snippets/vue/angle-slider/usage.mdx, website/package.json, website/sidebar.config.ts, website/styles/machines/angle-slider.css, website/styles/machines/index.css
=> chore: angle slider docs

website/data/components/file-upload.mdx
improve file-upload validate docs
Related #2025
=> chore: improve file-upload validate docs

website/sidebar.config.ts
=> chore: hide angle-slider docs

website/sidebar.config.ts
=> chore: show angle-slider docs

packages/docs/data/accessibility.json, website/data/components/angle-slider.mdx
update angle slider docs
Remove `rtl` support guide
=> chore: update angle slider docs

packages/docs/data/api.json, website/data/components/file-upload.mdx
document file upload validate details
=> chore: document file upload validate details

e2e/accordion.e2e.ts, e2e/tags-input.e2e.ts, examples/nuxt-ts/pages/tooltip.vue, examples/svelte-ts/src/routes/color-picker.svelte, scripts/visualize.ts
=> fix: :pencil2: spelling fix

website/components/showcase.tsx, website/data/components/carousel.mdx, website/data/snippets/react/carousel/usage.mdx, website/data/snippets/svelte/carousel/usage.mdx
=> chore: update carousel slides

website/data/snippets/solid/avatar/usage.mdx, website/data/snippets/solid/number-input/scrubber.mdx, website/data/snippets/solid/select/usage-with-form.mdx
=> chore(docs): fix solid snippets

packages/machines/select/src/select.types.ts, packages/machines/tree-view/src/index.ts
=> chore: Update tree view exports

.github/composite-actions/install/action.yml, .github/workflows/visualize.yml
Closes # 
Updated the version of `actions/setup-node` in the workflow files to ensure compatibility and leverage the latest features and fixes provided by the `v4` release.
The workflow currently uses an older version of `actions/setup-node` (e.g., v2 or v3), which may lack the latest updates or features available in the `v4` release.
The workflow now uses `actions/setup-node@v4`, providing improved performance, new features, and the latest fixes introduced in the updated version.
No
=> chore(.github): update action version in workflow files

website/components/showcase.tsx, website/data/components/popover.mdx
Updates docs for Popover to use `closeOnInteractOutside` and `closeOnEscape` instead of `closeOnBlur` and `closeOnEsc`
No
=> Update Docs for Popover

website/data/snippets/solid/switch/usage.mdx
=> docs: small fix in solid/switch usage example

packages/machines/timer/README.md
Closes # 
This PR changes the title from `@zag-js/checkbox` to `@zag-js/timer`
There's a typo in the package
The typo is fixed
No
=> Rename `@zag-js/checkbox` to `@zag-js/timer` to fix typo

website/data/overview/composition.mdx
Fixes small typo introduced in #2327
=> docs(composition): typo

.changeset/violet-comics-enjoy.md, examples/vanilla-ts/src/lib/machine.ts, packages/core/src/types.ts, packages/frameworks/preact/src/machine.ts, packages/frameworks/react/src/machine.ts, packages/frameworks/react/tests/machine.test.ts, packages/frameworks/solid/src/machine.ts, packages/frameworks/svelte/src/machine.svelte.ts, packages/frameworks/vue/src/machine.ts, packages/utilities/dom-query/src/set.ts, packages/utilities/remove-scroll/src/index.ts
Fixes some edge cases with Next.js and React
=> fix(*): implement machine status check

website/data/components/popover.mdx
Moves the arrow parts from the popover machine into the content.
Implementing the structure like this results in not correctly hiding the arrow.
Updates the snippet like its also implemented by the component itself. https://github.com/chakra-ui/zag/blob/4899e1d806e2367f2d7a7df8787d186cf1c3cd6e/website/components/machines/popover.tsx#L22C11-L26C1
No
X
=> docs: fix popover arrow snippet

website/data/components/listbox.mdx
=> docs(listbox): fix headings order

examples/vanilla-ts/src/combobox.ts
improve combobox vanilla example
=> chore: improve combobox vanilla example

website/data/overview/whats-a-machine.mdx
I think there current code of this function is invalid JS code. I fixed it by adding a return statement.
=> Fix getButtonProps in connect function example of whats-a-machine.mdx

website/data/components/password-input.mdx, website/data/snippets/react/password-input/usage.mdx, website/data/snippets/solid/password-input/usage.mdx, website/data/snippets/vue/password-input/usage.mdx
> Update snippets react, solid, and vue for password input
```js
const service = useMachine(passwordInput.machine({ id: useId() }))
```
```js
const service = useMachine(passwordInput.machine, { id: useId() })
```
No
=> docs: update snippets react, solid, and vue for password input

.changeset/sour-states-fail.md, packages/machines/progress/src/progress.machine.ts
Closes #2535
Fixed the issue where the orientation field passed by the user was overwritten by the default value.
=> fix(progress): orientation value assign

examples/next-ts/pages/color-picker-inline.tsx, shared/src/controls.ts, shared/src/routes.ts
Add color picker inline example
=> chore: update examples

.changeset/gentle-singers-push.md, packages/machines/floating-panel/src/floating-panel.connect.ts
=> chore(floating-panel): add data attributes for stage status

.changeset/few-dodos-wash.md, packages/machines/bottom-sheet/src/index.ts
Closes # 
Re-export some missing types:
- `ResolvedSnapPoint`
- `SnapPointChangeDetails`
- `ContentProps`
Some types are missing.
Add some missing types.
=> fix(bottom-sheet): re-export types
